(function(){function d(a){throw a;}var h=void 0,i=!0,m=null,n=!1;function aa(){return function(a){return a}}function p(){return function(){}}function q(a){return function(b){this[a]=b}}function r(a){return function(){return this[a]}}function t(a){return function(){return a}}var u,w=w||{};w.global=this;w.OC=n;w.RQ="en";w.cT=function(a){w.jK(a)};w.mT=function(a){w.OC||(a=a||"",d(Error("Importing test-only code into non-debug environment"+a?": "+a:".")))};
w.jK=function(a,b,c){a=a.split(".");c=c||w.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var e;a.length&&(e=a.shift());)!a.length&&w.dq(b)?c[e]=b:c=c[e]?c[e]:c[e]={}};w.EO=function(){for(var a=["window","event"],b=w.global,c;c=a.shift();)if(w.VO(b[c]))b=b[c];else return m;return b};w.wS=function(a,b){var c=b||w.global,e;for(e in a)c[e]=a[e]};w.rR=p();w.BQ=i;w.hT=p();w.ER="";w.aM=p();w.BS=aa();w.wa=function(){d(Error("unimplemented abstract method"))};
w.sR=function(a){a.kS=function(){return a.QO||(a.QO=new a)}};
w.wk=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};w.dq=function(a){return a!==h};w.JS=function(a){return a===m};w.VO=function(a){return a!=m};w.isArray=function(a){return"array"==w.wk(a)};w.of=function(a){var b=w.wk(a);return"array"==b||"object"==b&&"number"==typeof a.length};w.HS=function(a){return w.qo(a)&&"function"==typeof a.getFullYear};w.bd=function(a){return"string"==typeof a};w.SO=function(a){return"boolean"==typeof a};w.oL=function(a){return"number"==typeof a};
w.tA=function(a){return"function"==w.wk(a)};w.qo=function(a){var b=typeof a;return"object"==b&&a!=m||"function"==b};w.ao=function(a){return a[w.by]||(a[w.by]=++w.TP)};w.BP=function(a){"removeAttribute"in a&&a.removeAttribute(w.by);try{delete a[w.by]}catch(b){}};w.by="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36);w.TP=0;w.iS=w.ao;w.fT=w.BP;w.LN=function(a){var b=w.wk(a);if("object"==b||"array"==b){if(a.ja)return a.ja();var b="array"==b?[]:{},c;for(c in a)b[c]=w.LN(a[c]);return b}return a};
w.GN=function(a,b,c){return a.call.apply(a.bind,arguments)};w.FN=function(a,b,c){a||d(Error());if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};w.bind=function(a,b,c){w.bind=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?w.GN:w.FN;return w.bind.apply(m,arguments)};
w.jM=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};w.SS=function(a,b){for(var c in b)a[c]=b[c]};w.now=Date.now||function(){return+new Date};
w.vS=function(a){if(w.global.execScript)w.global.execScript(a,"JavaScript");else if(w.global.eval)if(w.rz==m&&(w.global.eval("var _et_ = 1;"),"undefined"!=typeof w.global._et_?(delete w.global._et_,w.rz=i):w.rz=n),w.rz)w.global.eval(a);else{var b=w.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=n;c.appendChild(b.createTextNode(a));b.body.appendChild(c);b.body.removeChild(c)}else d(Error("goog.globalEval not available"))};w.rz=m;
w.hS=function(a,b){function c(a){return w.IJ[a]||a}var e;e=w.IJ?"BY_WHOLE"==w.VN?c:function(a){for(var a=a.split("-"),b=[],e=0;e<a.length;e++)b.push(c(a[e]));return b.join("-")}:aa();return b?a+"-"+e(b):e(a)};w.iT=function(a,b){w.IJ=a;w.VN=b};w.nS=function(a,b){var c=b||{},e;for(e in c)var f=(""+c[e]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+e+"\\}","gi"),f);return a};w.gh=function(a,b){w.jK(a,b,h)};w.T=function(a,b,c){a[b]=c};
w.a=function(a,b){function c(){}c.prototype=b.prototype;a.b=b.prototype;a.prototype=new c;a.prototype.constructor=a};w.DR=function(a,b,c){var e=arguments.callee.caller;if(e.b)return e.b.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),g=n,j=a.constructor;j;j=j.b&&j.b.constructor)if(j.prototype[b]===e)g=i;else if(g)return j.prototype[b].apply(a,f);if(a[b]===e)return a.constructor.prototype[b].apply(a,f);d(Error("goog.base called from a method of one name to a method of a different name"))};
w.scope=function(a){a.call(w.global)};w.debug={};function ba(a){this.stack=Error().stack||"";a&&(this.message=""+a)}w.a(ba,Error);ba.prototype.name="CustomError";w.S={};w.S.OP=function(a){return 0==a.lastIndexOf("/",0)};w.S.lO=function(a){var b=a.length-1;return 0<=b&&a.indexOf("/",b)==b};w.S.NR=function(a,b){return 0==w.S.kJ(b,a.substr(0,b.length))};w.S.MR=function(a,b){return 0==w.S.kJ(b,a.substr(a.length-b.length,b.length))};w.S.PP=function(a,b){for(var c=1;c<arguments.length;c++)var e=(""+arguments[c]).replace(/\$/g,"$$$$"),a=a.replace(/\%s/,e);return a};w.S.RR=function(a){return a.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,"")};w.S.Ui=function(a){return/^[\s\xa0]*$/.test(a)};
w.S.IS=function(a){return w.S.Ui(w.S.eP(a))};w.S.GS=function(a){return!/[^\t\n\r ]/.test(a)};w.S.ES=function(a){return!/[^a-zA-Z]/.test(a)};w.S.KS=function(a){return!/[^0-9]/.test(a)};w.S.FS=function(a){return!/[^a-zA-Z0-9]/.test(a)};w.S.MS=function(a){return" "==a};w.S.NS=function(a){return 1==a.length&&" "<=a&&"~">=a||"\u0080"<=a&&"\ufffd">=a};w.S.rT=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")};w.S.LR=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")};
w.S.WS=function(a){return a.replace(/\xa0|\s/g," ")};w.S.VS=function(a){return a.replace(/\xa0|[ \t]+/g," ")};w.S.QR=function(a){return a.replace(/[\t\r\n ]+/g," ").replace(/^[\t\r\n ]+|[\t\r\n ]+$/g,"")};w.S.trim=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};w.S.trimLeft=function(a){return a.replace(/^[\s\xa0]+/,"")};w.S.trimRight=function(a){return a.replace(/[\s\xa0]+$/,"")};w.S.kJ=function(a,b){var c=(""+a).toLowerCase(),e=(""+b).toLowerCase();return c<e?-1:c==e?0:1};w.S.cM=/(\.\d+)|(\d+)|(\D+)/g;
w.S.XS=function(a,b){if(a==b)return 0;if(!a)return-1;if(!b)return 1;for(var c=a.toLowerCase().match(w.S.cM),e=b.toLowerCase().match(w.S.cM),f=Math.min(c.length,e.length),g=0;g<f;g++){var j=c[g],k=e[g];if(j!=k)return c=parseInt(j,10),!isNaN(c)&&(e=parseInt(k,10),!isNaN(e)&&c-e)?c-e:j<k?-1:1}return c.length!=e.length?c.length-e.length:a<b?-1:1};w.S.kO=/^[a-zA-Z0-9\-_.!~*'()]*$/;w.S.bu=function(a){a=""+a;return!w.S.kO.test(a)?encodeURIComponent(a):a};
w.S.wC=function(a){return decodeURIComponent(a.replace(/\+/g," "))};w.S.jP=function(a,b){return a.replace(/(\r\n|\r|\n)/g,b?"<br />":"<br>")};w.S.SK=function(a){if(!w.S.BN.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(w.S.CN,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(w.S.dP,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(w.S.KO,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(w.S.uP,"&quot;"));return a};w.S.CN=/&/g;w.S.dP=/</g;w.S.KO=/>/g;w.S.uP=/\"/g;w.S.BN=/[&<>\"]/;
w.S.fN=function(a){return w.S.contains(a,"&")?"document"in w.global?w.S.UP(a):w.S.VP(a):a};w.S.UP=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(w.S.wN,function(a,f){var g=b[a];if(g)return g;if("#"==f.charAt(0)){var j=Number("0"+f.substr(1));isNaN(j)||(g=String.fromCharCode(j))}g||(c.innerHTML=a+" ",g=c.firstChild.nodeValue.slice(0,-1));return b[a]=g})};
w.S.VP=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var e=Number("0"+c.substr(1));if(!isNaN(e))return String.fromCharCode(e)}return a}})};w.S.wN=/&([^;\s<&]+);?/g;w.S.ET=function(a,b){return w.S.jP(a.replace(/  /g," &#160;"),b)};
w.S.sT=function(a,b){for(var c=b.length,e=0;e<c;e++){var f=1==c?b:b.charAt(e);if(a.charAt(0)==f&&a.charAt(a.length-1)==f)return a.substring(1,a.length-1)}return a};w.S.truncate=function(a,b,c){c&&(a=w.S.fN(a));a.length>b&&(a=a.substring(0,b-3)+"...");c&&(a=w.S.SK(a));return a};
w.S.yT=function(a,b,c,e){c&&(a=w.S.fN(a));if(e&&a.length>b)e>b&&(e=b),a=a.substring(0,b-e)+"..."+a.substring(a.length-e);else if(a.length>b)var e=Math.floor(b/2),f=a.length-e,a=a.substring(0,e+b%2)+"..."+a.substring(f);c&&(a=w.S.SK(a));return a};w.S.WH={"\x00":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\"};w.S.CA={"'":"\\'"};
w.S.quote=function(a){a=""+a;if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var e=a.charAt(c),f=e.charCodeAt(0);b[c+1]=w.S.WH[e]||(31<f&&127>f?e:w.S.fK(e))}b.push('"');return b.join("")};w.S.$R=function(a){for(var b=[],c=0;c<a.length;c++)b[c]=w.S.fK(a.charAt(c));return b.join("")};
w.S.fK=function(a){if(a in w.S.CA)return w.S.CA[a];if(a in w.S.WH)return w.S.CA[a]=w.S.WH[a];var b=a,c=a.charCodeAt(0);if(31<c&&127>c)b=a;else{if(256>c){if(b="\\x",16>c||256<c)b+="0"}else b="\\u",4096>c&&(b+="0");b+=c.toString(16).toUpperCase()}return w.S.CA[a]=b};w.S.vT=function(a){for(var b={},c=0;c<a.length;c++)b[a.charAt(c)]=i;return b};w.S.contains=function(a,b){return-1!=a.indexOf(b)};w.S.TR=function(a,b){return a&&b?a.split(b).length-1:0};
w.S.rB=function(a,b,c){var e=a;0<=b&&b<a.length&&0<c&&(e=a.substr(0,b)+a.substr(b+c,a.length-b-c));return e};w.S.remove=function(a,b){var c=RegExp(w.S.tM(b),"");return a.replace(c,"")};w.S.wM=function(a,b){var c=RegExp(w.S.tM(b),"g");return a.replace(c,"")};w.S.tM=function(a){return(""+a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};w.S.repeat=function(a,b){return Array(b+1).join(a)};
w.S.ZS=function(a,b,c){a=w.dq(c)?a.toFixed(c):""+a;c=a.indexOf(".");-1==c&&(c=a.length);return w.S.repeat("0",Math.max(0,b-c))+a};w.S.eP=function(a){return a==m?"":""+a};w.S.HN=function(a){return Array.prototype.join.call(arguments,"")};w.S.HK=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^w.now()).toString(36)};
w.S.rJ=function(a,b){for(var c=0,e=w.S.trim(""+a).split("."),f=w.S.trim(""+b).split("."),g=Math.max(e.length,f.length),j=0;0==c&&j<g;j++){var k=e[j]||"",l=f[j]||"",o=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var v=o.exec(k)||["","",""],y=s.exec(l)||["","",""];if(0==v[0].length&&0==y[0].length)break;c=w.S.JD(0==v[1].length?0:parseInt(v[1],10),0==y[1].length?0:parseInt(y[1],10))||w.S.JD(0==v[2].length,0==y[2].length)||w.S.JD(v[2],y[2])}while(0==c)}return c};
w.S.JD=function(a,b){return a<b?-1:a>b?1:0};w.S.vN=4294967296;w.S.zS=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=w.S.vN;return b};w.S.XP=2147483648*Math.random()|0;w.S.VR=function(){return"goog_"+w.S.XP++};w.S.wT=function(a){var b=Number(a);return 0==b&&w.S.Ui(a)?NaN:b};w.S.aN={};w.S.uT=function(a){return w.S.aN[a]||(w.S.aN[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};w.S.bN={};
w.S.xT=function(a){return w.S.bN[a]||(w.S.bN[a]=(""+a).replace(/([A-Z])/g,"-$1").toLowerCase())};w.kd={};w.kd.Rl=w.OC;function ca(a,b){b.unshift(a);ba.call(this,w.S.PP.apply(m,b));b.shift()}w.a(ca,ba);ca.prototype.name="AssertionError";w.kd.Jn=function(a,b,c,e){var f="Assertion failed";if(c)var f=f+(": "+c),g=e;else a&&(f+=": "+a,g=b);d(new ca(""+f,g||[]))};w.kd.assert=function(a,b,c){w.kd.Rl&&!a&&w.kd.Jn("",m,b,Array.prototype.slice.call(arguments,2));return a};w.kd.bS=function(a,b){w.kd.Rl&&d(new ca("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1)))};
w.kd.AR=function(a,b,c){w.kd.Rl&&!w.oL(a)&&w.kd.Jn("Expected number but got %s: %s.",[w.wk(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.kd.CR=function(a,b,c){w.kd.Rl&&!w.bd(a)&&w.kd.Jn("Expected string but got %s: %s.",[w.wk(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.kd.yR=function(a,b,c){w.kd.Rl&&!w.tA(a)&&w.kd.Jn("Expected function but got %s: %s.",[w.wk(a),a],b,Array.prototype.slice.call(arguments,2));return a};
w.kd.BR=function(a,b,c){w.kd.Rl&&!w.qo(a)&&w.kd.Jn("Expected object but got %s: %s.",[w.wk(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.kd.wR=function(a,b,c){w.kd.Rl&&!w.isArray(a)&&w.kd.Jn("Expected array but got %s: %s.",[w.wk(a),a],b,Array.prototype.slice.call(arguments,2));return a};w.kd.xR=function(a,b,c){w.kd.Rl&&!w.SO(a)&&w.kd.Jn("Expected boolean but got %s: %s.",[w.wk(a),a],b,Array.prototype.slice.call(arguments,2));return a};
w.kd.zR=function(a,b,c,e){w.kd.Rl&&!(a instanceof b)&&w.kd.Jn("instanceof check failed.",m,c,Array.prototype.slice.call(arguments,3))};w.W={};w.$o=i;w.W.$S=function(a){return a[a.length-1]};w.W.ee=Array.prototype;w.W.indexOf=w.$o&&w.W.ee.indexOf?function(a,b,c){return w.W.ee.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(w.bd(a))return!w.bd(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
w.W.lastIndexOf=w.$o&&w.W.ee.lastIndexOf?function(a,b,c){return w.W.ee.lastIndexOf.call(a,b,c==m?a.length-1:c)}:function(a,b,c){c=c==m?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(w.bd(a))return!w.bd(b)||1!=b.length?-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};w.W.forEach=w.$o&&w.W.ee.forEach?function(a,b,c){w.W.ee.forEach.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=w.bd(a)?a.split(""):a,g=0;g<e;g++)g in f&&b.call(c,f[g],g,a)};
w.W.pO=function(a,b){for(var c=a.length,e=w.bd(a)?a.split(""):a,c=c-1;0<=c;--c)c in e&&b.call(h,e[c],c,a)};w.W.filter=w.$o&&w.W.ee.filter?function(a,b,c){return w.W.ee.filter.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=[],g=0,j=w.bd(a)?a.split(""):a,k=0;k<e;k++)if(k in j){var l=j[k];b.call(c,l,k,a)&&(f[g++]=l)}return f};
w.W.map=w.$o&&w.W.ee.map?function(a,b,c){return w.W.ee.map.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=Array(e),g=w.bd(a)?a.split(""):a,j=0;j<e;j++)j in g&&(f[j]=b.call(c,g[j],j,a));return f};w.W.reduce=function(a,b,c,e){if(a.reduce)return e?a.reduce(w.bind(b,e),c):a.reduce(b,c);var f=c;w.W.forEach(a,function(c,j){f=b.call(e,f,c,j,a)});return f};
w.W.reduceRight=function(a,b,c,e){if(a.reduceRight)return e?a.reduceRight(w.bind(b,e),c):a.reduceRight(b,c);var f=c;w.W.pO(a,function(c,j){f=b.call(e,f,c,j,a)});return f};w.W.some=w.$o&&w.W.ee.some?function(a,b,c){return w.W.ee.some.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=w.bd(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&b.call(c,f[g],g,a))return i;return n};
w.W.every=w.$o&&w.W.ee.every?function(a,b,c){return w.W.ee.every.call(a,b,c)}:function(a,b,c){for(var e=a.length,f=w.bd(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&!b.call(c,f[g],g,a))return n;return i};w.W.find=function(a,b,c){b=w.W.nK(a,b,c);return 0>b?m:w.bd(a)?a.charAt(b):a[b]};w.W.nK=function(a,b,c){for(var e=a.length,f=w.bd(a)?a.split(""):a,g=0;g<e;g++)if(g in f&&b.call(c,f[g],g,a))return g;return-1};w.W.cS=function(a,b,c){b=w.W.mO(a,b,c);return 0>b?m:w.bd(a)?a.charAt(b):a[b]};
w.W.mO=function(a,b,c){for(var e=a.length,f=w.bd(a)?a.split(""):a,e=e-1;0<=e;e--)if(e in f&&b.call(c,f[e],e,a))return e;return-1};w.W.contains=function(a,b){return 0<=w.W.indexOf(a,b)};w.W.Ui=function(a){return 0==a.length};w.W.clear=function(a){if(!w.isArray(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};w.W.CS=function(a,b){w.W.contains(a,b)||a.push(b)};w.W.ZK=function(a,b,c){w.W.splice(a,c,0,b)};w.W.DS=function(a,b,c){w.jM(w.W.splice,a,c,0).apply(m,b)};
w.W.insertBefore=function(a,b,c){var e;2==arguments.length||0>(e=w.W.indexOf(a,c))?a.push(b):w.W.ZK(a,b,e)};w.W.remove=function(a,b){var c=w.W.indexOf(a,b),e;(e=0<=c)&&w.W.rB(a,c);return e};w.W.rB=function(a,b){return 1==w.W.ee.splice.call(a,b,1).length};w.W.gT=function(a,b,c){b=w.W.nK(a,b,c);return 0<=b?(w.W.rB(a,b),i):n};w.W.concat=function(a){return w.W.ee.concat.apply(w.W.ee,arguments)};w.W.ja=function(a){if(w.isArray(a))return w.W.concat(a);for(var b=[],c=0,e=a.length;c<e;c++)b[c]=a[c];return b};
w.W.nI=function(a){return w.isArray(a)?w.W.concat(a):w.W.ja(a)};w.W.extend=function(a,b){for(var c=1;c<arguments.length;c++){var e=arguments[c],f;if(w.isArray(e)||(f=w.of(e))&&e.hasOwnProperty("callee"))a.push.apply(a,e);else if(f)for(var g=a.length,j=e.length,k=0;k<j;k++)a[g+k]=e[k];else a.push(e)}};w.W.splice=function(a,b,c,e){return w.W.ee.splice.apply(a,w.W.slice(arguments,1))};w.W.slice=function(a,b,c){return 2>=arguments.length?w.W.ee.slice.call(a,b):w.W.ee.slice.call(a,b,c)};
w.W.eT=function(a,b){for(var c=b||a,e={},f=0,g=0;g<a.length;){var j=a[g++],k=w.qo(j)?"o"+w.ao(j):(typeof j).charAt(0)+j;Object.prototype.hasOwnProperty.call(e,k)||(e[k]=i,c[f++]=j)}c.length=f};w.W.bJ=function(a,b,c){return w.W.cJ(a,c||w.W.zp,n,b)};w.W.HR=function(a,b,c){return w.W.cJ(a,b,i,h,c)};w.W.cJ=function(a,b,c,e,f){for(var g=0,j=a.length,k;g<j;){var l=g+j>>1,o;o=c?b.call(f,a[l],l,a):b(e,a[l]);0<o?g=l+1:(j=l,k=!o)}return k?g:~g};w.W.sort=function(a,b){w.W.ee.sort.call(a,b||w.W.zp)};
w.W.qT=function(a,b){for(var c=0;c<a.length;c++)a[c]={index:c,value:a[c]};var e=b||w.W.zp;w.W.sort(a,function(a,b){return e(a.value,b.value)||a.index-b.index});for(c=0;c<a.length;c++)a[c]=a[c].value};w.W.pT=function(a,b,c){var e=c||w.W.zp;w.W.sort(a,function(a,c){return e(a[b],c[b])})};w.W.LS=function(a,b,c){for(var b=b||w.W.zp,e=1;e<a.length;e++){var f=b(a[e-1],a[e]);if(0<f||0==f&&c)return n}return i};
w.W.zE=function(a,b,c){if(!w.of(a)||!w.of(b)||a.length!=b.length)return n;for(var e=a.length,c=c||w.W.WN,f=0;f<e;f++)if(!c(a[f],b[f]))return n;return i};w.W.NN=function(a,b,c){return w.W.zE(a,b,c)};w.W.SR=function(a,b,c){for(var c=c||w.W.zp,e=Math.min(a.length,b.length),f=0;f<e;f++){var g=c(a[f],b[f]);if(0!=g)return g}return w.W.zp(a.length,b.length)};w.W.zp=function(a,b){return a>b?1:a<b?-1:0};w.W.WN=function(a,b){return a===b};
w.W.FR=function(a,b,c){c=w.W.bJ(a,b,c);return 0>c?(w.W.ZK(a,b,-(c+1)),i):n};w.W.GR=function(a,b,c){b=w.W.bJ(a,b,c);return 0<=b?w.W.rB(a,b):n};w.W.IR=function(a,b){for(var c={},e=0;e<a.length;e++){var f=a[e],g=b(f,e,a);w.dq(g)&&(c[g]||(c[g]=[])).push(f)}return c};w.W.repeat=function(a,b){for(var c=[],e=0;e<b;e++)c[e]=a;return c};w.W.oO=function(a){for(var b=[],c=0;c<arguments.length;c++){var e=arguments[c];w.isArray(e)?b.push.apply(b,w.W.oO.apply(m,e)):b.push(e)}return b};
w.W.rotate=function(a,b){a.length&&(b%=a.length,0<b?w.W.ee.unshift.apply(a,a.splice(-b,b)):0>b&&w.W.ee.push.apply(a,a.splice(0,-b)));return a};w.W.FT=function(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var e=[],f=0;f<arguments.length;f++){var g=arguments[f];if(c>=g.length)return b;e.push(g[c])}b.push(e)}};w.W.oT=function(a,b){for(var c=b||Math.random,e=a.length-1;0<e;e--){var f=Math.floor(c()*(e+1)),g=a[e];a[e]=a[f];a[f]=g}};w.debug.mf={};w.debug.DQ=p();w.debug.mf.vt=[];w.debug.mf.FG=[];w.debug.mf.QL=n;w.debug.mf.uM=function(a){w.debug.mf.vt[w.debug.mf.vt.length]=a;if(w.debug.mf.QL)for(var b=w.debug.mf.FG,c=0;c<b.length;c++)a(w.bind(b[c].fQ,b[c]))};w.debug.mf.TS=function(a){w.debug.mf.QL=i;for(var b=w.bind(a.fQ,a),c=0;c<w.debug.mf.vt.length;c++)w.debug.mf.vt[c](b);w.debug.mf.FG.push(a)};w.debug.mf.AT=function(a){for(var b=w.debug.mf.FG,a=w.bind(a.CT,a),c=0;c<w.debug.mf.vt.length;c++)w.debug.mf.vt[c](a);b.length--};w.debug.ZR={pM:aa()};w.userAgent={};w.userAgent.FI=n;w.userAgent.EI=n;w.userAgent.JI=n;w.userAgent.MC=n;w.userAgent.II=n;w.userAgent.pN=n;w.userAgent.qr=w.userAgent.FI||w.userAgent.EI||w.userAgent.MC||w.userAgent.JI||w.userAgent.II;w.userAgent.NK=function(){return w.global.navigator?w.global.navigator.userAgent:m};w.userAgent.Pz=function(){return w.global.navigator};
w.userAgent.PO=function(){w.userAgent.rv=n;w.userAgent.QJ=n;w.userAgent.jz=n;w.userAgent.RJ=n;w.userAgent.PJ=n;var a;if(!w.userAgent.qr&&(a=w.userAgent.NK())){var b=w.userAgent.Pz();w.userAgent.rv=0==a.indexOf("Opera");w.userAgent.QJ=!w.userAgent.rv&&-1!=a.indexOf("MSIE");w.userAgent.jz=!w.userAgent.rv&&-1!=a.indexOf("WebKit");w.userAgent.RJ=w.userAgent.jz&&-1!=a.indexOf("Mobile");w.userAgent.PJ=!w.userAgent.rv&&!w.userAgent.jz&&"Gecko"==b.product}};w.userAgent.qr||w.userAgent.PO();
w.userAgent.PC=w.userAgent.qr?w.userAgent.II:w.userAgent.rv;w.userAgent.zk=w.userAgent.qr?w.userAgent.FI:w.userAgent.QJ;w.userAgent.$x=w.userAgent.qr?w.userAgent.EI:w.userAgent.PJ;w.userAgent.pn=w.userAgent.qr?w.userAgent.JI||w.userAgent.MC:w.userAgent.jz;w.userAgent.WQ=w.userAgent.MC||w.userAgent.RJ;w.userAgent.eR=w.userAgent.pn;w.userAgent.cO=function(){var a=w.userAgent.Pz();return a&&a.platform||""};w.userAgent.QC=w.userAgent.cO();w.userAgent.HI=n;w.userAgent.KI=n;w.userAgent.GI=n;
w.userAgent.LI=n;w.userAgent.su=w.userAgent.HI||w.userAgent.KI||w.userAgent.GI||w.userAgent.LI;w.userAgent.OO=function(){w.userAgent.$N=w.S.contains(w.userAgent.QC,"Mac");w.userAgent.aO=w.S.contains(w.userAgent.QC,"Win");w.userAgent.ZN=w.S.contains(w.userAgent.QC,"Linux");w.userAgent.bO=!!w.userAgent.Pz()&&w.S.contains(w.userAgent.Pz().appVersion||"","X11")};w.userAgent.su||w.userAgent.OO();w.userAgent.TQ=w.userAgent.su?w.userAgent.HI:w.userAgent.$N;w.userAgent.pR=w.userAgent.su?w.userAgent.KI:w.userAgent.aO;
w.userAgent.PQ=w.userAgent.su?w.userAgent.GI:w.userAgent.ZN;w.userAgent.qR=w.userAgent.su?w.userAgent.LI:w.userAgent.bO;w.userAgent.dO=function(){var a="",b;w.userAgent.PC&&w.global.opera?(a=w.global.opera.version,a="function"==typeof a?a():a):(w.userAgent.$x?b=/rv\:([^\);]+)(\)|;)/:w.userAgent.zk?b=/MSIE\s+([^\);]+)(\)|;)/:w.userAgent.pn&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(w.userAgent.NK()))?a[1]:""));return w.userAgent.zk&&(b=w.userAgent.wO(),b>parseFloat(a))?""+b:a};
w.userAgent.wO=function(){var a=w.global.document;return a?a.documentMode:h};w.userAgent.VERSION=w.userAgent.dO();w.userAgent.NN=function(a,b){return w.S.rJ(a,b)};w.userAgent.yL={};w.userAgent.kq=function(a){return w.userAgent.pN||w.userAgent.yL[a]||(w.userAgent.yL[a]=0<=w.S.rJ(w.userAgent.VERSION,a))};w.userAgent.fL={};w.userAgent.eL=function(){return w.userAgent.fL[9]||(w.userAgent.fL[9]=w.userAgent.zk&&!!document.documentMode&&9<=document.documentMode)};w.C={};!w.userAgent.zk||w.userAgent.eL();var ea=!w.userAgent.zk||w.userAgent.eL(),fa=w.userAgent.zk&&!w.userAgent.kq("8");!w.userAgent.pn||w.userAgent.kq("528");w.userAgent.$x&&w.userAgent.kq("1.9b")||w.userAgent.zk&&w.userAgent.kq("8")||w.userAgent.PC&&w.userAgent.kq("9.5")||w.userAgent.pn&&w.userAgent.kq("528");!w.userAgent.$x||w.userAgent.kq("8");w.eO={};w.eO.KQ=p();function ha(){}ha.prototype.WJ=n;ha.prototype.Hj=function(){this.WJ||(this.WJ=i,this.In())};ha.prototype.In=function(){this.XN&&w.VJ.apply(m,this.XN)};w.Hj=function(a){a&&"function"==typeof a.Hj&&a.Hj()};w.VJ=function(a){for(var b=0,c=arguments.length;b<c;++b){var e=arguments[b];w.of(e)?w.VJ.apply(m,e):w.Hj(e)}};function ia(a,b){this.type=a;this.currentTarget=this.target=b}w.a(ia,ha);u=ia.prototype;u.In=function(){delete this.type;delete this.target;delete this.currentTarget};u.Pq=n;u.$w=i;u.stopPropagation=function(){this.Pq=i};u.preventDefault=function(){this.$w=n};ia.stopPropagation=function(a){a.stopPropagation()};ia.preventDefault=function(a){a.preventDefault()};var x={NC:"click",uQ:"dblclick",Zo:"mousedown",rr:"mouseup",vi:"mouseover",ui:"mouseout",ti:"mousemove",hR:"selectstart",NQ:"keypress",MQ:"keydown",OQ:"keyup",nQ:"blur",FQ:"focus",vQ:"deactivate",GQ:w.userAgent.zk?"focusin":"DOMFocusIn",HQ:w.userAgent.zk?"focusout":"DOMFocusOut",pQ:"change",gR:"select",iR:"submit",LQ:"input",cR:"propertychange",zQ:"dragstart",wQ:"dragenter",yQ:"dragover",xQ:"dragleave",AQ:"drop",mR:"touchstart",lR:"touchmove",kR:"touchend",jR:"touchcancel",rQ:"contextmenu",CQ:"error",
JQ:"help",QQ:"load",SQ:"losecapture",dR:"readystatechange",ay:"resize",fR:"scroll",oR:"unload",IQ:"hashchange",ZQ:"pagehide",$Q:"pageshow",bR:"popstate",sQ:"copy",aR:"paste",tQ:"cut",kQ:"beforecopy",lQ:"beforecut",mQ:"beforepaste",UQ:"message",qQ:"connect",nR:w.userAgent.pn?"webkitTransitionEnd":w.userAgent.PC?"oTransitionEnd":"transitionend"};w.Rq={};w.Rq.object=function(a,b){return b};w.Rq.TH=function(a){w.Rq.TH[" "](a);return a};w.Rq.TH[" "]=w.aM;w.Rq.IN=function(a){try{return w.Rq.TH(a.nodeName),i}catch(b){}return n};function ja(a,b){a&&this.Pj(a,b)}w.a(ja,ia);u=ja.prototype;u.target=m;u.relatedTarget=m;u.offsetX=0;u.offsetY=0;u.clientX=0;u.clientY=0;u.screenX=0;u.screenY=0;u.button=0;u.keyCode=0;u.charCode=0;u.ctrlKey=n;u.altKey=n;u.shiftKey=n;u.metaKey=n;u.gs=m;
u.Pj=function(a,b){var c=this.type=a.type;ia.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var e=a.relatedTarget;e?w.userAgent.$x&&(w.Rq.IN(e)||(e=m)):c==x.vi?e=a.fromElement:c==x.ui&&(e=a.toElement);this.relatedTarget=e;this.offsetX=w.userAgent.pn||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=w.userAgent.pn||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.gs=a;delete this.$w;delete this.Pq};u.stopPropagation=function(){ja.b.stopPropagation.call(this);this.gs.stopPropagation?this.gs.stopPropagation():this.gs.cancelBubble=i};
u.preventDefault=function(){ja.b.preventDefault.call(this);var a=this.gs;if(a.preventDefault)a.preventDefault();else if(a.returnValue=n,fa)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};u.In=function(){ja.b.In.call(this);this.relatedTarget=this.currentTarget=this.target=this.gs=m};w.C.OI=p();w.C.OI.prototype.Za=p();w.C.OI.prototype.gc=p();function la(){}var ma=0;u=la.prototype;u.key=0;u.Sq=n;u.vD=n;u.Pj=function(a,b,c,e,f,g){w.tA(a)?this.jL=i:a&&a.handleEvent&&w.tA(a.handleEvent)?this.jL=n:d(Error("Invalid listener argument"));this.ft=a;this.qM=b;this.src=c;this.type=e;this.capture=!!f;this.bA=g;this.vD=n;this.key=++ma;this.Sq=n};u.handleEvent=function(a){return this.jL?this.ft.call(this.bA||this.src,a):this.ft.handleEvent.call(this.ft,a)};w.object={};w.object.forEach=function(a,b,c){for(var e in a)b.call(c,a[e],e,a)};w.object.filter=function(a,b,c){var e={},f;for(f in a)b.call(c,a[f],f,a)&&(e[f]=a[f]);return e};w.object.map=function(a,b,c){var e={},f;for(f in a)e[f]=b.call(c,a[f],f,a);return e};w.object.some=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return i;return n};w.object.every=function(a,b,c){for(var e in a)if(!b.call(c,a[e],e,a))return n;return i};w.object.Wn=function(a){var b=0,c;for(c in a)b++;return b};
w.object.fS=function(a){for(var b in a)return b};w.object.gS=function(a){for(var b in a)return a[b]};w.object.contains=function(a,b){return w.object.Yr(a,b)};w.object.Sf=function(a){var b=[],c=0,e;for(e in a)b[c++]=a[e];return b};w.object.Dg=function(a){var b=[],c=0,e;for(e in a)b[c++]=e;return b};w.object.uS=function(a,b){for(var c=w.of(b),e=c?b:arguments,c=c?0:1;c<e.length&&!(a=a[e[c]],!w.dq(a));c++);return a};w.object.Nk=function(a,b){return b in a};
w.object.Yr=function(a,b){for(var c in a)if(a[c]==b)return i;return n};w.object.nO=function(a,b,c){for(var e in a)if(b.call(c,a[e],e,a))return e};w.object.dS=function(a,b,c){return(b=w.object.nO(a,b,c))&&a[b]};w.object.Ui=function(a){for(var b in a)return n;return i};w.object.clear=function(a){for(var b in a)delete a[b]};w.object.remove=function(a,b){var c;(c=b in a)&&delete a[b];return c};
w.object.add=function(a,b,c){b in a&&d(Error('The object already contains the key "'+b+'"'));w.object.set(a,b,c)};w.object.get=function(a,b,c){return b in a?a[b]:c};w.object.set=function(a,b,c){a[b]=c};w.object.lT=function(a,b,c){return b in a?a[b]:a[b]=c};w.object.ja=function(a){var b={},c;for(c in a)b[c]=a[c];return b};w.object.YP=function(a){var b=w.wk(a);if("object"==b||"array"==b){if(a.ja)return a.ja();var b="array"==b?[]:{},c;for(c in a)b[c]=w.object.YP(a[c]);return b}return a};
w.object.SP=function(a){var b={},c;for(c in a)b[a[c]]=c;return b};w.object.RI="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");w.object.extend=function(a,b){for(var c,e,f=1;f<arguments.length;f++){e=arguments[f];for(c in e)a[c]=e[c];for(var g=0;g<w.object.RI.length;g++)c=w.object.RI[g],Object.prototype.hasOwnProperty.call(e,c)&&(a[c]=e[c])}};
w.object.create=function(a){var b=arguments.length;if(1==b&&w.isArray(arguments[0]))return w.object.create.apply(m,arguments[0]);b%2&&d(Error("Uneven number of arguments"));for(var c={},e=0;e<b;e+=2)c[arguments[e]]=arguments[e+1];return c};w.object.SN=function(a){var b=arguments.length;if(1==b&&w.isArray(arguments[0]))return w.object.SN.apply(m,arguments[0]);for(var c={},e=0;e<b;e++)c[arguments[e]]=i;return c};w.C.jQ=n;w.C.qe={};w.C.qh={};w.C.Il={};w.C.pP="on";w.C.RG={};w.C.OS="_";
w.C.Za=function(a,b,c,e,f){if(b){if(w.isArray(b)){for(var g=0;g<b.length;g++)w.C.Za(a,b[g],c,e,f);return m}var e=!!e,j=w.C.qh;b in j||(j[b]={Nc:0,ej:0});j=j[b];e in j||(j[e]={Nc:0,ej:0},j.Nc++);var j=j[e],k=w.ao(a),l;j.ej++;if(j[k]){l=j[k];for(g=0;g<l.length;g++)if(j=l[g],j.ft==c&&j.bA==f){if(j.Sq)break;return l[g].key}}else l=j[k]=[],j.Nc++;g=w.C.HO();g.src=a;j=new la;j.Pj(c,g,a,b,e,f);c=j.key;g.key=c;l.push(j);w.C.qe[c]=j;w.C.Il[k]||(w.C.Il[k]=[]);w.C.Il[k].push(j);a.addEventListener?(a==w.global||
!a.JJ)&&a.addEventListener(b,g,e):a.attachEvent(w.C.DK(b),g);return c}d(Error("Invalid event type"))};w.C.HO=function(){var a=w.C.Uv,b=ea?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b};w.C.bP=function(a,b,c,e,f){if(w.isArray(b))for(var g=0;g<b.length;g++)w.C.bP(a,b[g],c,e,f);else a=w.C.Za(a,b,c,e,f),w.C.qe[a].vD=i};w.C.PS=function(a,b,c,e,f){b.Za(a,c,e,f)};
w.C.gc=function(a,b,c,e,f){if(w.isArray(b)){for(var g=0;g<b.length;g++)w.C.gc(a,b[g],c,e,f);return m}e=!!e;a=w.C.$E(a,b,e);if(!a)return n;for(g=0;g<a.length;g++)if(a[g].ft==c&&a[g].capture==e&&a[g].bA==f)return w.C.tC(a[g].key);return n};
w.C.tC=function(a){if(!w.C.qe[a])return n;var b=w.C.qe[a];if(b.Sq)return n;var c=b.src,e=b.type,f=b.qM,g=b.capture;c.removeEventListener?(c==w.global||!c.JJ)&&c.removeEventListener(e,f,g):c.detachEvent&&c.detachEvent(w.C.DK(e),f);c=w.ao(c);f=w.C.qh[e][g][c];if(w.C.Il[c]){var j=w.C.Il[c];w.W.remove(j,b);0==j.length&&delete w.C.Il[c]}b.Sq=i;f.ZL=i;w.C.oJ(e,g,c,f);delete w.C.qe[a];return i};w.C.zT=function(a,b,c,e,f){b.gc(a,c,e,f)};
w.C.oJ=function(a,b,c,e){if(!e.IA&&e.ZL){for(var f=0,g=0;f<e.length;f++)e[f].Sq?e[f].qM.src=m:(f!=g&&(e[g]=e[f]),g++);e.length=g;e.ZL=n;0==g&&(delete w.C.qh[a][b][c],w.C.qh[a][b].Nc--,0==w.C.qh[a][b].Nc&&(delete w.C.qh[a][b],w.C.qh[a].Nc--),0==w.C.qh[a].Nc&&delete w.C.qh[a])}};
w.C.wM=function(a,b,c){var e=0,f=b==m,g=c==m,c=!!c;if(a==m)w.object.forEach(w.C.Il,function(a){for(var j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(g||c==k.capture))w.C.tC(k.key),e++}});else if(a=w.ao(a),w.C.Il[a])for(var a=w.C.Il[a],j=a.length-1;0<=j;j--){var k=a[j];if((f||b==k.type)&&(g||c==k.capture))w.C.tC(k.key),e++}return e};w.C.mS=function(a,b,c){return w.C.$E(a,b,c)||[]};w.C.$E=function(a,b,c){var e=w.C.qh;return b in e&&(e=e[b],c in e&&(e=e[c],a=w.ao(a),e[a]))?e[a]:m};
w.C.lS=function(a,b,c,e,f){e=!!e;if(a=w.C.$E(a,b,e))for(b=0;b<a.length;b++)if(!a[b].Sq&&a[b].ft==c&&a[b].capture==e&&a[b].bA==f)return a[b];return m};w.C.xS=function(a,b,c){var a=w.ao(a),e=w.C.Il[a];if(e){var f=w.dq(b),g=w.dq(c);return f&&g?(e=w.C.qh[b],!!e&&!!e[c]&&a in e[c]):!f&&!g?i:w.W.some(e,function(a){return f&&a.type==b||g&&a.capture==c})}return n};w.C.aS=function(a){var b=[],c;for(c in a)a[c]&&a[c].id?b.push(c+" = "+a[c]+" ("+a[c].id+")"):b.push(c+" = "+a[c]);return b.join("\n")};
w.C.DK=function(a){return a in w.C.RG?w.C.RG[a]:w.C.RG[a]=w.C.pP+a};w.C.eS=function(a,b,c,e){var f=w.C.qh;return b in f&&(f=f[b],c in f)?w.C.ks(f[c],a,b,c,e):i};w.C.ks=function(a,b,c,e,f){var g=1,b=w.ao(b);if(a[b]){a.ej--;a=a[b];a.IA?a.IA++:a.IA=1;try{for(var j=a.length,k=0;k<j;k++){var l=a[k];l&&!l.Sq&&(g&=w.C.GE(l,f)!==n)}}finally{a.IA--,w.C.oJ(c,e,b,a)}}return Boolean(g)};w.C.GE=function(a,b){var c=a.handleEvent(b);a.vD&&w.C.tC(a.key);return c};w.C.sS=function(){return w.object.Wn(w.C.qe)};
w.C.dispatchEvent=function(a,b){var c=b.type||b,e=w.C.qh;if(!(c in e))return i;if(w.bd(b))b=new ia(b,a);else if(b instanceof ia)b.target=b.target||a;else{var f=b,b=new ia(c,a);w.object.extend(b,f)}var f=1,g,e=e[c],c=i in e,j;if(c){g=[];for(j=a;j;j=j.YG)g.push(j);j=e[i];j.ej=j.Nc;for(var k=g.length-1;!b.Pq&&0<=k&&j.ej;k--)b.currentTarget=g[k],f&=w.C.ks(j,g[k],b.type,i,b)&&b.$w!=n}if(n in e)if(j=e[n],j.ej=j.Nc,c)for(k=0;!b.Pq&&k<g.length&&j.ej;k++)b.currentTarget=g[k],f&=w.C.ks(j,g[k],b.type,n,b)&&
b.$w!=n;else for(e=a;!b.Pq&&e&&j.ej;e=e.YG)b.currentTarget=e,f&=w.C.ks(j,e,b.type,n,b)&&b.$w!=n;return Boolean(f)};w.C.aT=function(a){w.C.Uv=a.pM(w.C.Uv)};
w.C.Uv=function(a,b){if(!w.C.qe[a])return i;var c=w.C.qe[a],e=c.type,f=w.C.qh;if(!(e in f))return i;var f=f[e],g,j;if(!ea){g=b||w.EO();var k=i in f,l=n in f;if(k){if(w.C.XO(g))return i;w.C.gP(g)}var o=new ja;o.Pj(g,this);g=i;try{if(k){for(var s=[],v=o.currentTarget;v;v=v.parentNode)s.push(v);j=f[i];j.ej=j.Nc;for(var y=s.length-1;!o.Pq&&0<=y&&j.ej;y--)o.currentTarget=s[y],g&=w.C.ks(j,s[y],e,i,o);if(l){j=f[n];j.ej=j.Nc;for(y=0;!o.Pq&&y<s.length&&j.ej;y++)o.currentTarget=s[y],g&=w.C.ks(j,s[y],e,n,o)}}else g=
w.C.GE(c,o)}finally{s&&(s.length=0),o.Hj()}return g}e=new ja(b,this);try{g=w.C.GE(c,e)}finally{e.Hj()}return g};w.C.gP=function(a){var b=n;if(0==a.keyCode)try{a.keyCode=-1;return}catch(c){b=i}if(b||a.returnValue==h)a.returnValue=i};w.C.XO=function(a){return 0>a.keyCode||a.returnValue!=h};w.C.WP=0;w.C.tS=function(a){return a+"_"+w.C.WP++};w.debug.mf.uM(function(a){w.C.Uv=a(w.C.Uv)});function na(){}w.a(na,ha);u=na.prototype;u.JJ=i;u.YG=m;u.addEventListener=function(a,b,c,e){w.C.Za(this,a,b,c,e)};u.removeEventListener=function(a,b,c,e){w.C.gc(this,a,b,c,e)};u.dispatchEvent=function(a){return w.C.dispatchEvent(this,a)};u.In=function(){na.b.In.call(this);w.C.wM(this);this.YG=m};var oa=w.global.window;w.lw={};w.lw.ZO=function(a){return/^\s*$/.test(a)?n:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};w.lw.parse=function(a){a=""+a;if(w.lw.ZO(a))try{return eval("("+a+")")}catch(b){}d(Error("Invalid JSON string: "+a))};w.lw.BT=function(a){return eval("("+a+")")};w.lw.$a=function(a,b){return(new pa(b)).$a(a)};
function pa(a){this.sB=a}pa.prototype.$a=function(a){var b=[];qa(this,a,b);return b.join("")};
function qa(a,b,c){switch(typeof b){case "string":ra(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(w.isArray(b)){var e=b.length;c.push("[");for(var f="",g=0;g<e;g++)c.push(f),f=b[g],qa(a,a.sB?a.sB.call(b,""+g,f):f,c),f=",";c.push("]");break}c.push("{");e="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(f=b[g],"function"!=typeof f&&(c.push(e),ra(g,c),
c.push(":"),qa(a,a.sB?a.sB.call(b,g,f):f,c),e=","));c.push("}");break;case "function":break;default:d(Error("Unknown type: "+typeof b))}}var sa={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ta=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function ra(a,b){b.push('"',a.replace(ta,function(a){if(a in sa)return sa[a];var b=a.charCodeAt(0),f="\\u";16>b?f+="000":256>b?f+="00":4096>b&&(f+="0");return sa[a]=f+b.toString(16)}),'"')};w.Yj={};function ua(){}ua.prototype.iJ=m;ua.prototype.Nv=function(){var a;if(!(a=this.iJ))a={},va(this)&&(a[0]=i,a[1]=i),a=this.iJ=a;return a};function wa(a,b){this.gQ=a;this.sP=b}w.a(wa,ua);wa.prototype.OD=function(){return this.gQ()};wa.prototype.Nv=function(){return this.sP()};w.Yj.Ak=function(){return w.Yj.Ak.lK.OD()};w.Yj.Ak.Nv=function(){return w.Yj.Ak.lK.Nv()};w.Yj.Ak.jT=function(a,b){w.Yj.Ak.HM(new wa(a,b))};w.Yj.Ak.HM=function(a){w.Yj.Ak.lK=a};function xa(){}w.a(xa,ua);xa.prototype.OD=function(){var a=va(this);return a?new ActiveXObject(a):new XMLHttpRequest};xa.prototype.EF=m;
function va(a){if(!a.EF&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var e=b[c];try{return new ActiveXObject(e),a.EF=e}catch(f){}}d(Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed"))}return a.EF}w.Yj.Ak.HM(new xa);w.Sd={};w.Sd.Wn=function(a){return"function"==typeof a.Wn?a.Wn():w.of(a)||w.bd(a)?a.length:w.object.Wn(a)};w.Sd.Sf=function(a){if("function"==typeof a.Sf)return a.Sf();if(w.bd(a))return a.split("");if(w.of(a)){for(var b=[],c=a.length,e=0;e<c;e++)b.push(a[e]);return b}return w.object.Sf(a)};w.Sd.Dg=function(a){if("function"==typeof a.Dg)return a.Dg();if("function"!=typeof a.Sf){if(w.of(a)||w.bd(a)){for(var b=[],a=a.length,c=0;c<a;c++)b.push(c);return b}return w.object.Dg(a)}};
w.Sd.contains=function(a,b){return"function"==typeof a.contains?a.contains(b):"function"==typeof a.Yr?a.Yr(b):w.of(a)||w.bd(a)?w.W.contains(a,b):w.object.Yr(a,b)};w.Sd.Ui=function(a){return"function"==typeof a.Ui?a.Ui():w.of(a)||w.bd(a)?w.W.Ui(a):w.object.Ui(a)};w.Sd.clear=function(a){"function"==typeof a.clear?a.clear():w.of(a)?w.W.clear(a):w.object.clear(a)};
w.Sd.forEach=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(w.of(a)||w.bd(a))w.W.forEach(a,b,c);else for(var e=w.Sd.Dg(a),f=w.Sd.Sf(a),g=f.length,j=0;j<g;j++)b.call(c,f[j],e&&e[j],a)};w.Sd.filter=function(a,b,c){if("function"==typeof a.filter)return a.filter(b,c);if(w.of(a)||w.bd(a))return w.W.filter(a,b,c);var e,f=w.Sd.Dg(a),g=w.Sd.Sf(a),j=g.length;if(f){e={};for(var k=0;k<j;k++)b.call(c,g[k],f[k],a)&&(e[f[k]]=g[k])}else{e=[];for(k=0;k<j;k++)b.call(c,g[k],h,a)&&e.push(g[k])}return e};
w.Sd.map=function(a,b,c){if("function"==typeof a.map)return a.map(b,c);if(w.of(a)||w.bd(a))return w.W.map(a,b,c);var e,f=w.Sd.Dg(a),g=w.Sd.Sf(a),j=g.length;if(f){e={};for(var k=0;k<j;k++)e[f[k]]=b.call(c,g[k],f[k],a)}else{e=[];for(k=0;k<j;k++)e[k]=b.call(c,g[k],h,a)}return e};w.Sd.some=function(a,b,c){if("function"==typeof a.some)return a.some(b,c);if(w.of(a)||w.bd(a))return w.W.some(a,b,c);for(var e=w.Sd.Dg(a),f=w.Sd.Sf(a),g=f.length,j=0;j<g;j++)if(b.call(c,f[j],e&&e[j],a))return i;return n};
w.Sd.every=function(a,b,c){if("function"==typeof a.every)return a.every(b,c);if(w.of(a)||w.bd(a))return w.W.every(a,b,c);for(var e=w.Sd.Dg(a),f=w.Sd.Sf(a),g=f.length,j=0;j<g;j++)if(!b.call(c,f[j],e&&e[j],a))return n;return i};w.vb={};w.vb.eg="StopIteration"in w.global?w.global.StopIteration:Error("StopIteration");function ya(){}ya.prototype.next=function(){d(w.vb.eg)};ya.prototype.RC=function(){return this};w.vb.oi=function(a){if(a instanceof ya)return a;if("function"==typeof a.RC)return a.RC(n);if(w.of(a)){var b=0,c=new ya;c.next=function(){for(;;){b>=a.length&&d(w.vb.eg);if(b in a)return a[b++];b++}};return c}d(Error("Not implemented"))};
w.vb.forEach=function(a,b,c){if(w.of(a))try{w.W.forEach(a,b,c)}catch(e){e!==w.vb.eg&&d(e)}else{a=w.vb.oi(a);try{for(;;)b.call(c,a.next(),h,a)}catch(f){f!==w.vb.eg&&d(f)}}};w.vb.filter=function(a,b,c){var a=w.vb.oi(a),e=new ya;e.next=function(){for(;;){var e=a.next();if(b.call(c,e,h,a))return e}};return e};
w.vb.dT=function(a,b,c){var e=0,f=a,g=c||1;1<arguments.length&&(e=a,f=b);0==g&&d(Error("Range step argument must not be zero"));var j=new ya;j.next=function(){(g>0&&e>=f||g<0&&e<=f)&&d(w.vb.eg);var a=e;e=e+g;return a};return j};w.vb.join=function(a,b){return w.vb.nI(a).join(b)};w.vb.map=function(a,b,c){var a=w.vb.oi(a),e=new ya;e.next=function(){for(;;){var e=a.next();return b.call(c,e,h,a)}};return e};w.vb.reduce=function(a,b,c,e){var f=c;w.vb.forEach(a,function(a){f=b.call(e,f,a)});return f};
w.vb.some=function(a,b,c){a=w.vb.oi(a);try{for(;;)if(b.call(c,a.next(),h,a))return i}catch(e){e!==w.vb.eg&&d(e)}return n};w.vb.every=function(a,b,c){a=w.vb.oi(a);try{for(;;)if(!b.call(c,a.next(),h,a))return n}catch(e){e!==w.vb.eg&&d(e)}return i};w.vb.OR=function(a){var b=arguments,c=b.length,e=0,f=new ya;f.next=function(){try{return e>=c&&d(w.vb.eg),w.vb.oi(b[e]).next()}catch(a){return(a!==w.vb.eg||e>=c)&&d(a),e++,this.next()}};return f};
w.vb.YR=function(a,b,c){var a=w.vb.oi(a),e=new ya,f=i;e.next=function(){for(;;){var e=a.next();if(!f||!b.call(c,e,h,a))return f=n,e}};return e};w.vb.tT=function(a,b,c){var a=w.vb.oi(a),e=new ya,f=i;e.next=function(){for(;;)if(f){var e=a.next();if(b.call(c,e,h,a))return e;f=n}else d(w.vb.eg)};return e};w.vb.nI=function(a){if(w.of(a))return w.W.nI(a);var a=w.vb.oi(a),b=[];w.vb.forEach(a,function(a){b.push(a)});return b};
w.vb.zE=function(a,b){var a=w.vb.oi(a),b=w.vb.oi(b),c,e;try{for(;;){c=e=n;var f=a.next();c=i;var g=b.next();e=i;if(f!=g)break}}catch(j){j!==w.vb.eg&&d(j);if(c&&!e)return n;if(!e)try{b.next()}catch(k){return k!==w.vb.eg&&d(k),i}}return n};w.vb.US=function(a,b){try{return w.vb.oi(a).next()}catch(c){return c!=w.vb.eg&&d(c),b}};
w.vb.product=function(a){if(w.W.some(arguments,function(a){return!a.length})||!arguments.length)return new ya;var b=new ya,c=arguments,e=w.W.repeat(0,c.length);b.next=function(){if(e){for(var a=w.W.map(e,function(a,b){return c[b][a]}),b=e.length-1;0<=b;b--){if(e[b]<c[b].length-1){e[b]++;break}if(0==b){e=m;break}e[b]=0}return a}d(w.vb.eg)};return b};
w.vb.WR=function(a){var b=w.vb.oi(a),c=[],e=0,a=new ya,f=n;a.next=function(){var a=m;if(!f)try{return a=b.next(),c.push(a),a}catch(j){(j!=w.vb.eg||w.W.Ui(c))&&d(j),f=i}a=c[e];e=(e+1)%c.length;return a};return a};function za(a,b){this.sh={};this.Ya=[];var c=arguments.length;if(1<c){c%2&&d(Error("Uneven number of arguments"));for(var e=0;e<c;e+=2)this.set(arguments[e],arguments[e+1])}else if(a){a instanceof za?(c=a.Dg(),e=a.Sf()):(c=w.object.Dg(a),e=w.object.Sf(a));for(var f=0;f<c.length;f++)this.set(c[f],e[f])}}u=za.prototype;u.Nc=0;u.Sx=0;u.Wn=r("Nc");u.Sf=function(){Aa(this);for(var a=[],b=0;b<this.Ya.length;b++)a.push(this.sh[this.Ya[b]]);return a};u.Dg=function(){Aa(this);return this.Ya.concat()};
u.Nk=function(a){return Ba(this.sh,a)};u.Yr=function(a){for(var b=0;b<this.Ya.length;b++){var c=this.Ya[b];if(Ba(this.sh,c)&&this.sh[c]==a)return i}return n};u.zE=function(a,b){if(this===a)return i;if(this.Nc!=a.Wn())return n;var c=b||Ca;Aa(this);for(var e,f=0;e=this.Ya[f];f++)if(!c(this.get(e),a.get(e)))return n;return i};function Ca(a,b){return a===b}u.Ui=function(){return 0==this.Nc};u.clear=function(){this.sh={};this.Sx=this.Nc=this.Ya.length=0};
u.remove=function(a){return Ba(this.sh,a)?(delete this.sh[a],this.Nc--,this.Sx++,this.Ya.length>2*this.Nc&&Aa(this),i):n};function Aa(a){if(a.Nc!=a.Ya.length){for(var b=0,c=0;b<a.Ya.length;){var e=a.Ya[b];Ba(a.sh,e)&&(a.Ya[c++]=e);b++}a.Ya.length=c}if(a.Nc!=a.Ya.length){for(var f={},c=b=0;b<a.Ya.length;)e=a.Ya[b],Ba(f,e)||(a.Ya[c++]=e,f[e]=1),b++;a.Ya.length=c}}u.get=function(a,b){return Ba(this.sh,a)?this.sh[a]:b};
u.set=function(a,b){Ba(this.sh,a)||(this.Nc++,this.Ya.push(a),this.Sx++);this.sh[a]=b};u.ja=function(){return new za(this)};u.SP=function(){for(var a=new za,b=0;b<this.Ya.length;b++){var c=this.Ya[b];a.set(this.sh[c],c)}return a};u.RC=function(a){Aa(this);var b=0,c=this.Ya,e=this.sh,f=this.Sx,g=this,j=new ya;j.next=function(){for(;;){f!=g.Sx&&d(Error("The map has changed since the iterator was created"));b>=c.length&&d(w.vb.eg);var j=c[b++];return a?j:e[j]}};return j};
function Ba(a,b){return Object.prototype.hasOwnProperty.call(a,b)};w.uri={};w.uri.P={};w.uri.P.fJ=function(a,b,c,e,f,g,j){var k=[];a&&k.push(a,":");c&&(k.push("//"),b&&k.push(b,"@"),k.push(c),e&&k.push(":",e));f&&k.push(f);g&&k.push("?",g);j&&k.push("#",j);return k.join("")};w.uri.P.NP=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$");w.uri.P.split=function(a){return a.match(w.uri.P.NP)};w.uri.P.cz=function(a){return a&&decodeURIComponent(a)};
w.uri.P.vs=function(a,b){return w.uri.P.split(b)[a]||m};w.uri.P.jF=function(a){return w.uri.P.vs(1,a)};w.uri.P.yO=function(a){a=w.uri.P.jF(a);!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1));return a?a.toLowerCase():""};w.uri.P.JO=function(a){return w.uri.P.vs(2,a)};w.uri.P.OK=function(a){return w.uri.P.cz(w.uri.P.JO(a))};w.uri.P.xO=function(a){return w.uri.P.vs(3,a)};w.uri.P.wK=function(a){return w.uri.P.cz(w.uri.P.xO(a))};
w.uri.P.eF=function(a){return Number(w.uri.P.vs(4,a))||m};w.uri.P.GO=function(a){return w.uri.P.vs(5,a)};w.uri.P.Ov=function(a){return w.uri.P.cz(w.uri.P.GO(a))};w.uri.P.GK=function(a){return w.uri.P.vs(6,a)};w.uri.P.AO=function(a){var b=a.indexOf("#");return 0>b?m:a.substr(b+1)};w.uri.P.kT=function(a,b){return w.uri.P.zP(a)+(b?"#"+b:"")};w.uri.P.yK=function(a){return w.uri.P.cz(w.uri.P.AO(a))};w.uri.P.jS=function(a){a=w.uri.P.split(a);return w.uri.P.fJ(a[1],a[2],a[3],a[4])};
w.uri.P.rS=function(a){a=w.uri.P.split(a);return w.uri.P.fJ(m,m,m,m,a[5],a[6],a[7])};w.uri.P.zP=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};w.uri.P.AS=function(a,b){var c=w.uri.P.split(a),e=w.uri.P.split(b);return c[3]==e[3]&&c[1]==e[1]&&c[4]==e[4]};w.uri.P.EN=function(a){w.OC&&(0<=a.indexOf("#")||0<=a.indexOf("?"))&&d(Error("goog.uri.utils: Fragment or query identifiers are not supported: ["+a+"]"))};
w.uri.P.TC=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=h)}return a.join("")};w.uri.P.YI=function(a,b,c){if(w.isArray(b))for(var e=0;e<b.length;e++)c.push("&",a),""!==b[e]&&c.push("=",w.S.bu(b[e]));else b!=m&&(c.push("&",a),""!==b&&c.push("=",w.S.bu(b)))};w.uri.P.lD=function(a,b,c){for(c=c||0;c<b.length;c+=2)w.uri.P.YI(b[c],b[c+1],a);return a};
w.uri.P.JR=function(a,b){var c=w.uri.P.lD([],a,b);c[0]="";return c.join("")};w.uri.P.gJ=function(a,b){for(var c in b)w.uri.P.YI(c,b[c],a);return a};w.uri.P.KR=function(a){a=w.uri.P.gJ([],a);a[0]="";return a.join("")};w.uri.P.tR=function(a,b){return w.uri.P.TC(2==arguments.length?w.uri.P.lD([a],arguments[1],0):w.uri.P.lD([a],arguments,1))};w.uri.P.uR=function(a,b){return w.uri.P.TC(w.uri.P.gJ([a],b))};w.uri.P.DN=function(a,b){return w.uri.P.TC([a,"&","zx","=",w.S.bu(b)])};
w.uri.P.xz=function(a,b,c,e){for(var f=c.length;0<=(b=a.indexOf(c,b))&&b<e;){var g=a.charCodeAt(b-1);if(38==g||63==g)if(g=a.charCodeAt(b+f),!g||61==g||38==g||35==g)return b;b+=f+1}return-1};w.uri.P.cA=/#|$/;w.uri.P.yS=function(a,b){return 0<=w.uri.P.xz(a,0,b,a.search(w.uri.P.cA))};w.uri.P.pS=function(a,b){var c=a.search(w.uri.P.cA),e=w.uri.P.xz(a,0,b,c);if(0>e)return m;var f=a.indexOf("&",e);if(0>f||f>c)f=c;e+=b.length+1;return w.S.wC(a.substr(e,f-e))};
w.uri.P.qS=function(a,b){for(var c=a.search(w.uri.P.cA),e=0,f,g=[];0<=(f=w.uri.P.xz(a,e,b,c));){e=a.indexOf("&",f);if(0>e||e>c)e=c;f+=b.length+1;g.push(w.S.wC(a.substr(f,e-f)))}return g};w.uri.P.RP=/[?&]($|#)/;w.uri.P.AP=function(a){for(var b=a.search(w.uri.P.cA),c=0,e,f=[];0<=(e=w.uri.P.xz(a,c,"zx",b));)f.push(a.substring(c,e)),c=Math.min(a.indexOf("&",e)+1||b,b);f.push(a.substr(c));return f.join("").replace(w.uri.P.RP,"$1")};
w.uri.P.LP=function(a){var b=w.S.HK();return w.uri.P.DN(w.uri.P.AP(a),b)};w.uri.P.vR=function(a,b){w.uri.P.EN(a);w.S.lO(a)&&(a=a.substr(0,a.length-1));w.S.OP(b)&&(b=b.substr(1));return w.S.HN(a,"/",b)};w.uri.P.fP=function(a){return w.uri.P.LP(a)};function Da(a){na.call(this);this.headers=new za;this.JC=a||m}w.a(Da,na);Da.NI="Content-Type";Da.xN=/^https?$/i;Da.uN="application/x-www-form-urlencoded;charset=utf-8";Da.uH=[];Da.send=function(a,b,c,e,f,g){var j=new Da;Da.uH.push(j);b&&w.C.Za(j,"complete",b);w.C.Za(j,"ready",w.jM(Da.KN,j));g&&(j.mI=Math.max(0,g));j.send(a,c,e,f)};Da.PR=function(){for(var a=Da.uH;a.length;)a.pop().Hj()};Da.bT=function(a){Da.prototype.Iw=a.pM(Da.prototype.Iw)};Da.KN=function(a){a.Hj();w.W.remove(Da.uH,a)};u=Da.prototype;
u.qn=n;u.Rc=m;u.IC=m;u.FL="";u.AE=n;u.gA=n;u.FF=n;u.Wp=n;u.mI=0;u.jr=m;u.zM="";u.zI=n;
u.send=function(a,b,c,e){this.Rc&&d(Error("[goog.net.XhrIo] Object is active with another request"));b=b?b.toUpperCase():"GET";this.FL=a;this.AE=n;this.qn=i;this.Rc=this.JC?this.JC.OD():w.Yj.Ak();this.IC=this.JC?this.JC.Nv():w.Yj.Ak.Nv();this.Rc.onreadystatechange=w.bind(this.iM,this);try{this.FF=i,this.Rc.open(b,a,i),this.FF=n}catch(f){Ea(this);return}var a=c||"",g=this.headers.ja();e&&w.Sd.forEach(e,function(a,b){g.set(b,a)});"POST"==b&&!g.Nk(Da.NI)&&g.set(Da.NI,Da.uN);w.Sd.forEach(g,function(a,
b){this.Rc.setRequestHeader(b,a)},this);this.zM&&(this.Rc.responseType=this.zM);w.object.Nk(this.Rc,"withCredentials")&&(this.Rc.withCredentials=this.zI);try{this.jr&&(oa.clearTimeout(this.jr),this.jr=m),0<this.mI&&(this.jr=oa.setTimeout(w.bind(this.QP,this),this.mI)),this.gA=i,this.Rc.send(a),this.gA=n}catch(j){Ea(this)}};u.QP=function(){"undefined"!=typeof w&&this.Rc&&(this.dispatchEvent("timeout"),this.abort(8))};function Ea(a){a.qn=n;a.Rc&&(a.Wp=i,a.Rc.abort(),a.Wp=n);Fa(a);Ga(a)}
function Fa(a){a.AE||(a.AE=i,a.dispatchEvent("complete"),a.dispatchEvent("error"))}u.abort=function(){this.Rc&&this.qn&&(this.qn=n,this.Wp=i,this.Rc.abort(),this.Wp=n,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Ga(this))};u.In=function(){this.Rc&&(this.qn&&(this.qn=n,this.Wp=i,this.Rc.abort(),this.Wp=n),Ga(this,i));Da.b.In.call(this)};u.iM=function(){!this.FF&&!this.gA&&!this.Wp?this.Iw():Ha(this)};u.Iw=function(){Ha(this)};
function Ha(a){if(a.qn&&"undefined"!=typeof w&&(!a.IC[1]||!(4==(a.Rc?a.Rc.readyState:0)&&2==Ia(a))))if(a.gA&&4==(a.Rc?a.Rc.readyState:0))oa.setTimeout(w.bind(a.iM,a),0);else if(a.dispatchEvent("readystatechange"),4==(a.Rc?a.Rc.readyState:0)){a.qn=n;var b=Ia(a),c;a:switch(b){case 200:case 201:case 202:case 204:case 304:case 1223:c=i;break a;default:c=n}if(!c){if(b=0===b)b=w.uri.P.yO(""+a.FL),b=!Da.xN.test(b);c=b}c?(a.dispatchEvent("complete"),a.dispatchEvent("success")):Fa(a);Ga(a)}}
function Ga(a,b){if(a.Rc){var c=a.Rc,e=a.IC[0]?w.aM:m;a.Rc=m;a.IC=m;a.jr&&(oa.clearTimeout(a.jr),a.jr=m);b||a.dispatchEvent("ready");try{c.onreadystatechange=e}catch(f){}}}function Ia(a){try{return 2<(a.Rc?a.Rc.readyState:0)?a.Rc.status:-1}catch(b){return-1}}w.debug.mf.uM(function(a){Da.prototype.Iw=a(Da.prototype.Iw)});function Ja(a){a=typeof a;return"string"==a||"number"==a||"boolean"==a}function Ka(a){return"string"!=typeof a&&"undefined"!=typeof a.length}
function La(a,b){var c="<"+a;"undefined"!=typeof b.functionName&&(b["function"]=b.functionName,delete b.functionName);for(var e in b)"format"!=e&&"text"!=e&&"custom_attribute_value"!=e&&"attr"!=e&&Ja(b[e])&&(c+=" "+e+'="'+b[e]+'"');c+=">";for(e in b)if("arg"==e&&Ka(b[e]))for(var f=b[e],g=0;g<f.length;g++)c+="<arg><![CDATA["+f[g]+"]]\></arg>";else if("custom_attribute_value"==e||"attr"==e)c+="<![CDATA["+b[e]+"]]\>";else if("format"==e||"text"==e)c+="<"+e+"><![CDATA["+b[e]+"]]\></"+e+">";else if(Ka(b[e])){f=
b[e];for(g=0;g<f.length;g++)c+=La(e,f[g])}else Ja(b[e])||(c+=La(e,b[e]));return c+("</"+a+">")}function Ma(){}u=Ma.prototype;u.ka=m;u.A=m;u.Sn=m;u.ZA=m;u.YA=m;u.YL=m;u.LG=m;u.wz=m;u.Pj=function(a){this.ka=a;this.LG=this.YL=this.YA=this.ZA=this.ym=n;this.Ci=this.ka.enableFirefoxPrintPreviewFix};u.ym=n;u.dM=function(){this.ym=i;this.ZA&&this.kj(this.ka.xmlFile);this.YA&&this.mi(this.ka.xmlData);this.YL&&this.Oo(this.ka.jsonFile);this.LG&&this.mk(this.ka.jsonData)};u.eM=function(){this.Ci&&Na(this)};
u.fd=t(m);u.Xv=function(){this.ka.visible=n;this.A&&(this.A.style.visibility="hidden",this.A.setAttribute("width","1px"),this.A.setAttribute("height","1px"))};u.show=function(){this.ka.visible=i;this.A&&(this.A.style.visibility="visible",this.A.setAttribute("width",this.Ka+""),this.A.setAttribute("height",this.hb+""))};
u.ds=function(a,b){a&&"OBJECT"==a.nodeName&&(z.platform.Ts&&z.platform.lq?(a.style.display="none",function(){4==a.readyState?(z.platform.rl&&b!=m&&Oa(window[b]),Oa(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))};u.mp=function(){return z.platform.AF&&this.ka.swfFile!=m};
u.write=function(a){var b=this.ka.width+"",c=this.ka.height+"",e=this.ka.preloaderSWFFile?this.ka.preloaderSWFFile:this.ka.swfFile;if(this.Ci=this.Ci&&z.platform.hL)this.wz=new Pa;if(z.platform.Ts&&z.platform.lq){var f;f='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+(' id="'+this.ka.id+'"');f=f+(' width="'+b+'"')+(' height="'+c+'"')+(' style="visibility:'+(this.ka.visible?"visible":"hidden")+'"');f+=' codebase="'+z.platform.protocol+'//fpdownload.macromedia.com/get/flashplayer/current/swflash.cab">';
f+=Qa("movie",e);f+=Qa("bgcolor",this.ka.bgColor);f+=Qa("allowScriptAccess","always");f+=Qa("flashvars",Ra(this));this.ka.wMode!=m&&(f+=Qa("wmode",this.ka.wMode));f+="</object>";if(z.platform.rl){b=m;for(c=a;c;){if(c.nodeName!=m&&"form"==c.nodeName.toLowerCase()){b=c;break}c=c.parentNode}if(b!=m){window[this.ka.id]={};window[this.ka.id].yN=p();a.innerHTML=f;window[this.ka.id].yN=m;var a={},g;for(g in window[this.ka.id])"function"==typeof window[this.ka.id][g]&&(a[g]=window[this.ka.id][g]);this.A=
window[this.ka.id]=b[this.ka.id];this.ka.flashObject=this.A;for(g in a)Sa(g)}else a.innerHTML=f,this.A=document.getElementById(this.ka.id),this.ka.flashObject=this.A}else a.innerHTML=f,this.A=document.getElementById(this.ka.id),this.ka.flashObject=this.A}else{g=document.createElement("object");g.setAttribute("type","application/x-shockwave-flash");g.setAttribute("id",this.ka.id);g.setAttribute("width",b);g.setAttribute("height",c);g.setAttribute("data",e);g.setAttribute("style","visibility: "+(this.ka.visible?
"visible":"hidden"));Ta(g,"movie",e);Ta(g,"bgcolor",this.ka.bgColor);Ta(g,"allowScriptAccess","always");Ta(g,"flashvars",Ra(this));this.ka.wMode!=m&&Ta(g,"wmode",this.ka.wMode);if(a.hasChildNodes())for(;0<a.childNodes.length;)a.removeChild(a.firstChild);this.A=a.appendChild(g);this.ka.flashObject=this.A;this.Sn=a}return this.A!=m};function Qa(a,b){return'<param name="'+a+'" value="'+b+'" />'}
function Ta(a,b,c){var e=document.createElement("param");e.setAttribute("name",b);e.setAttribute("value",c);a.appendChild(e)}function Sa(a){eval('obj[functionName] = function(){return eval(this.CallFunction("<invoke name=\\"'+a+'\\" returntype=\\"javascript\\">" + __flash__argumentsToXML(arguments,0) + "</invoke>"));}')}
function Ra(a){var b="__externalobjid="+a.ka.id;a.ka.preloaderSWFFile&&(b+="&swffile="+a.ka.swfFile);a.ka.xmlFile&&(b+="&xmlfile="+a.ka.xmlFile);a.ka.enabledChartEvents&&(b+="&__enableevents=1");a.ka.enabledChartMouseEvents&&(b+="&__enablechartmouseevents=1");b+="&preloaderInit="+a.ka.messages.preloaderInit;b+="&preloaderLoading="+a.ka.messages.preloaderLoading;b+="&init="+a.ka.messages.init;b+="&loadingConfig="+a.ka.messages.loadingConfig;b+="&loadingTemplates="+a.ka.messages.loadingTemplates;b+=
"&loadingResources="+a.ka.messages.loadingResources;b+="&noData="+a.ka.messages.noData;return b+="&waitingForData="+a.ka.messages.waitingForData}u.Lu=t(i);u.vC=function(){(this.Ci||this.Sn)&&this.wz.Hj();Na(this)};u.$q=function(a,b){this.A&&(this.A.setAttribute("width",a+""),this.A.setAttribute("height",b+""))};
u.remove=function(){this.A&&(this.A.Dispose&&this.A.Dispose(),Ua(this.A,this.jo),this.Ci&&(this.Ci||this.Sn)&&this.wz.Hj());this.A=m;this.ka.flashObject=this.A;if(z&&z.LO())for(var a=z.CK(),b=0;b<a;b++)if(z.uK()[b]==this){z.uK().splice(b,1);break}z&&z.vK()&&this.jo!=m&&(z.vK()[this.jo]=m)};u.clear=function(){this.A&&this.A.Clear&&this.A.Clear()};u.refresh=function(){this.A!=m&&this.A.Refresh!=m&&this.A.Refresh()};u.Yt=function(a,b){this.A!=m&&this.A.UpdateData!=m&&this.A.UpdateData(a,b)};
u.LB=function(a){this.A&&this.A.SetLoading&&this.A.SetLoading(a)};u.Fz=function(){return this.A.GetInformation()};u.kj=function(a){this.A&&this.ym?this.A.SetXMLDataFromURL(a):this.ZA=i};u.mi=function(a){this.A&&this.ym?this.A.SetXMLDataFromString(a):this.YA=i};u.Oo=p();u.mk=function(a){this.A&&this.ym?this.mi(La("anychart",a)):this.LG=i};u.ox=function(a){this.A&&this.ym?this.A.SetXMLDataFromString(a):this.YA=i};u.TB=function(a){this.A&&this.ym?this.A.SetXMLDataFromURL(a):this.ZA=i};
u.br=function(a,b){this.A&&this.ym&&this.A.UpdateViewFromURL(a,b)};u.PB=function(a,b){this.A&&this.ym&&this.A.UpdateViewFromString(a,b)};u.od=function(a,b){this.A!=m&&this.A.AddPoint!=m&&this.A.AddPoint(a,b)};u.Bk=function(a,b,c){this.A!=m&&this.A.AddPointAt!=m&&this.A.AddPointAt(a,b,c)};u.yl=function(a,b){this.A!=m&&this.A.RemovePoint!=m&&this.A.RemovePoint(a,b)};u.Nl=function(a,b,c){this.A!=m&&this.A.UpdatePoint!=m&&this.A.UpdatePoint(a,b,c)};
u.xk=function(a,b,c){this.A!=m&&this.A.UpdatePointData!=m&&this.A.UpdatePointData(a,b,c)};u.bl=function(a,b,c){this.A!=m&&this.A.HighlightPoint!=m&&this.A.HighlightPoint(a,b,c)};u.ik=function(a,b,c){this.A!=m&&this.A.SelectPoint!=m&&this.A.SelectPoint(a,b,c)};u.uC=function(a,b,c,e){this.A&&this.A.updatePointWithAnimation!=m&&this.A.updatePointWithAnimation(a,b,c,e)};u.dC=function(){this.A&&this.A.startPointsUpdate!=m&&this.A.startPointsUpdate()};u.Ck=function(a){this.A!=m&&this.A.AddSeries!=m&&this.A.AddSeries(a)};
u.Dk=function(a,b){this.A!=m&&this.A.AddSeriesAt!=m&&this.A.AddSeriesAt(a,b)};u.zl=function(a){this.A!=m&&this.A.RemoveSeries!=m&&this.A.RemoveSeries(a)};u.Ol=function(a,b){this.A!=m&&this.A.UpdateSeries!=m&&this.A.UpdateSeries(a,b)};u.Hl=function(a,b){this.A!=m&&this.A.ShowSeries!=m&&this.A.ShowSeries(a,b)};u.cl=function(a,b){this.A!=m&&this.A.HighlightSeries!=m&&this.A.HighlightSeries(a,b)};u.al=function(a,b){this.A!=m&&this.A.HighlightCategory!=m&&this.A.HighlightCategory(a,b)};
u.$B=function(a,b){this.A!=m&&this.A.ShowAxisMarker!=m&&this.A.ShowAxisMarker(a,b)};u.Dl=function(a,b){this.A!=m&&this.A.SetPlotCustomAttribute!=m&&this.A.SetPlotCustomAttribute(a,b)};u.ou=function(a,b,c){this.A!=m&&this.A.View_SetPlotCustomAttribute!=m&&this.A.View_SetPlotCustomAttribute(a,b,c)};u.fu=function(a,b){this.A!=m&&this.A.View_AddSeries!=m&&this.A.View_AddSeries(a,b)};u.mu=function(a,b){this.A!=m&&this.A.View_RemoveSeries!=m&&this.A.View_RemoveSeries(a,b)};
u.gu=function(a,b,c){this.A!=m&&this.A.View_AddSeriesAt!=m&&this.A.View_AddSeriesAt(a,b,c)};u.ru=function(a,b,c){this.A!=m&&this.A.View_UpdateSeries!=m&&this.A.View_UpdateSeries(a,b,c)};u.pu=function(a,b,c){this.A!=m&&this.A.View_ShowSeries!=m&&this.A.View_ShowSeries(a,b,c)};u.du=function(a,b,c){this.A!=m&&this.A.View_AddPoint!=m&&this.A.View_AddPoint(a,b,c)};u.eu=function(a,b,c,e){this.A!=m&&this.A.View_AddPointAt!=m&&this.A.View_AddPointAt(a,b,c,e)};
u.lu=function(a,b,c){this.A!=m&&this.A.View_RemovePoint!=m&&this.A.View_RemovePoint(a,b,c)};u.qu=function(a,b,c,e){this.A!=m&&this.A.View_UpdatePoint!=m&&this.A.View_UpdatePoint(a,b,c,e)};u.EC=function(a){this.A!=m&&this.A.View_Clear!=m&&this.A.View_Clear(a)};u.ku=function(a){this.A!=m&&this.A.View_Refresh!=m&&this.A.View_Refresh(a)};u.ju=function(a,b,c){this.A!=m&&this.A.View_HighlightSeries!=m&&this.A.View_HighlightSeries(a,b,c)};
u.iu=function(a,b,c,e){this.A!=m&&this.A.View_HighlightPoint!=m&&this.A.View_HighlightPoint(a,b,c,e)};u.hu=function(a,b,c){this.A!=m&&this.A.View_HighlightCategory!=m&&this.A.View_HighlightCategory(a,b,c)};u.nu=function(a,b,c,e){this.A!=m&&this.A.View_SelectPoint!=m&&this.A.View_SelectPoint(a,b,c,e)};u.$t=function(a,b,c,e){this.A!=m&&this.A.UpdateViewPointData!=m&&this.A.UpdateViewPointData(a,b,c,e)};u.zs=function(a,b){return this.A.GetPngScreen(a,b)};
u.Sz=function(a,b){return this.A.GetPdfScreen(a,b)};u.pB=function(){this.A.PrintChart()};u.CB=function(a,b){this.A.SaveAsImage(a,b)};u.DB=function(a,b){this.A.SaveAsPDF(a,b)};u.EB=function(a){this.A!=m&&this.A.ScrollXTo!=m&&this.A.ScrollXTo(a)};u.FB=function(a){this.A!=m&&this.A.ScrollYTo!=m&&this.A.ScrollYTo(a)};u.scrollTo=function(a,b){this.A!=m&&this.A.ScrollTo!=m&&this.A.ScrollTo(a,b)};u.BC=function(a,b){this.A!=m&&this.A.ViewScrollXTo!=m&&this.A.ViewScrollXTo(a,b)};
u.CC=function(a,b){this.A!=m&&this.A.ViewScrollYTo!=m&&this.A.ViewScrollYTo(a,b)};u.Yz=function(){return this.A!=m&&this.A.GetXScrollInfo!=m?this.A.GetXScrollInfo():m};u.Zz=function(){return this.A!=m&&this.A.GetYScrollInfo!=m?this.A.GetYScrollInfo():m};u.Wz=function(a){if(this.A!=m&&this.A.GetViewXScrollInfo!=m)return this.A.GetViewXScrollInfo(a)};u.Xz=function(a){if(this.A!=m&&this.A.GetViewYScrollInfo!=m)return this.A.GetViewYScrollInfo(a)};u.UB=function(a){this.A!=m&&this.A.SetXZoom!=m&&this.A.SetXZoom(a)};
u.VB=function(a){this.A!=m&&this.A.SetYZoom!=m&&this.A.SetYZoom(a)};u.WB=function(a,b){this.A!=m&&this.A.SetZoom!=m&&this.A.SetZoom(a,b)};u.QB=function(a,b){this.A!=m&&this.A.SetViewXZoom!=m&&this.A.SetViewXZoom(a,b)};u.RB=function(a,b){this.A!=m&&this.A.SetViewYZoom!=m&&this.A.SetViewYZoom(a,b)};u.SB=function(a,b,c){this.A!=m&&this.A.SetViewZoom!=m&&this.A.SetViewZoom(a,b,c)};u.hy=function(){this.A!=m&&this.A.RepeatAnimation!=m&&this.A.RepeatAnimation()};
function Ua(a,b){a&&"OBJECT"==a.nodeName&&(z.platform.Ts&&z.platform.lq?(a.style.display="none",function(){4==a.readyState?(z.platform.rl&&b&&Oa(window[b]),Oa(a)):setTimeout(arguments.callee,10)}()):a.parentNode.removeChild(a))}function Oa(a){for(var b in a)"function"==typeof a[b]&&(a[b]=m);a.parentNode&&a.parentNode.removeChild(a)}
function Na(a){if(a.Ci&&a.Sn){var b=a.zs();if(b&&0!=b.length){var c=a.Sn.getAttribute("id");c||(c="__chart_generated_container__"+a.jo,a.Sn.setAttribute("id",c));var e=a.wz,f=a.Sn,g=a.Ka+"",j=a.hb+"",a=a.Sn.nodeName,k=document.getElementsByTagName("head");if(k=0<k.length?k[0]:m){var l;l=k;var o=document.createElement("style");o.setAttribute("type","text/css");o.setAttribute("media","screen");var s=a+"#"+c,v=s+" img";o.appendChild(document.createTextNode(s+(" object { width:"+g+"; height:"+j+";padding:0; margin:0; }\n")));
o.appendChild(document.createTextNode(v+" { display: none; }"));l=l.appendChild(o);e.xv=l;l=document.createElement("style");l.setAttribute("type","text/css");l.setAttribute("media","print");a=a+"#"+c;c=a+" img";g=" { display: block; width: "+g+"; height: "+j+"; }";l.appendChild(document.createTextNode(a+" object { display: none; }\n"));l.appendChild(document.createTextNode(c+g));g=k.appendChild(l);e.yv=g;g=document.createElement("img");g=f.appendChild(g);g.src="data:image/png;base64,"+b;e.wv=g}}}}
function Pa(){}u.xv=m;u.yv=m;u.wv=m;Pa.prototype.Hj=function(){this.wv&&this.wv.parentNode&&this.wv.parentNode.removeChild(this.wv);this.xv&&(this.xv.parentNode.removeChild(this.xv),this.xv=m);this.yv&&(this.yv.parentNode.removeChild(this.yv),this.yv=m)};w.gh("anychart.scope.goog",w);w.gh("anychart.scope.Event",ia);w.gh("anychart.scope.EventTarget",na);w.gh("anychart.scope.EventType",x);w.gh("anychart.scope.XhrIo",Da);var Va={};w.gh("anychart.WMode",Va);w.T(Va,"WINDOW","window");w.T(Va,"TRANSPARENT","transparent");w.T(Va,"OPAQUE","opaque");var Wa={};w.gh("anychart.RenderingType",Wa);w.T(Wa,"FLASH_ONLY","flash");w.T(Wa,"SVG_ONLY","svg");w.T(Wa,"FLASH_PREFERRED","flashPreferred");w.T(Wa,"SVG_PREFERRED","svgPreferred");
function z(a,b,c){c&&(this.id=c);this.swfFile=z.swfFile;this.preloaderSWFFile=z.preloaderSWFFile;this.width=z.width;this.height=z.height;this.enableFirefoxPrintPreviewFix=z.enableFirefoxPrintPreviewFix;this.enabledChartEvents=z.enabledChartEvents;this.enabledChartMouseEvents=z.enabledChartMouseEvents;this.renderingType=z.renderingType;this.watermark=z.watermark;this.messages.preloaderInit=z.messages.preloaderInit;this.messages.preloaderLoading=z.messages.preloaderLoading;this.messages.init=z.messages.init;
this.messages.loadingConfig=z.messages.loadingConfig;this.messages.loadingResources=z.messages.loadingResources;this.messages.loadingTemplates=z.messages.loadingTemplates;this.messages.noData=z.messages.noData;this.messages.waitingForData=z.messages.waitingForData;a&&(this.swfFile=a);b&&(this.preloaderSWFFile=b);this.qe={};z.yP(this)}w.gh("AnyChart",z);z.VERSION="6.0.12 (build #39628)";w.T(z,"VERSION",z.VERSION);z.width=550;w.T(z,"width",z.width);z.height=400;w.T(z,"height",z.height);z.mH="flash";
w.T(z,"renderingType",z.mH);z.uE=i;w.T(z,"enabledChartEvents",z.uE);z.vE=n;w.T(z,"enabledChartMouseEvents",z.vE);z.kI=m;w.T(z,"swfFile",z.kI);z.jH=m;w.T(z,"preloaderSWFFile",z.jH);z.Ci=i;w.T(z,"enableFirefoxPrintPreviewFix",z.Ci);z.prototype.id=m;w.T(z.prototype,"id",z.prototype.id);z.Pu=[];z.LO=function(){return z.Pu&&0<z.CK()};z.CK=function(){return z.Pu.length};z.uK=function(){return z.Pu};z.Rr={};z.vK=function(){return z.Rr};z.prototype.mH=m;w.T(z.prototype,"renderingType",z.prototype.mH);
z.prototype.sa=m;z.prototype.gl=n;z.prototype.iQ=m;w.T(z.prototype,"xmlFile",z.prototype.iQ);z.prototype.aP=m;w.T(z.prototype,"jsonFile",z.prototype.aP);z.prototype.hQ=m;w.T(z.prototype,"xmlData",z.prototype.hQ);z.prototype.$O=m;w.T(z.prototype,"jsonData",z.prototype.$O);z.prototype.width=m;w.T(z.prototype,"width",z.prototype.width);z.prototype.height=m;w.T(z.prototype,"height",z.prototype.height);z.prototype.eQ=m;w.T(z.prototype,"watermark",z.prototype.eQ);z.prototype.kI=m;
w.T(z.prototype,"swfFile",z.prototype.kI);z.prototype.jH=m;w.T(z.prototype,"preloaderSWFFile",z.prototype.jH);z.prototype.Ci=i;w.T(z.prototype,"enableFirefoxPrintPreviewFix",z.prototype.Ci);z.prototype.dQ=m;w.T(z.prototype,"wMode",z.prototype.dQ);z.prototype.uE=i;w.T(z.prototype,"enabledChartEvents",z.prototype.uE);z.prototype.vE=n;w.T(z.prototype,"enabledChartMouseEvents",z.prototype.vE);z.prototype.qe=m;z.prototype.bgColor="#FFFFFF";w.T(z.prototype,"bgColor",z.prototype.bgColor);
z.prototype.cQ=i;w.T(z.prototype,"visible",z.prototype.cQ);z.prototype.show=function(){this.visible=i;this.sa.show()};w.T(z.prototype,"show",z.prototype.show);z.prototype.Xv=function(){this.visible=n;this.sa.Xv()};w.T(z.prototype,"hide",z.prototype.Xv);z.P={};z.P.zF=function(a){return"undefined"!=typeof a};z.P.push=function(a,b){a[a.length]=b};var Xa=navigator&&navigator.userAgent?navigator.userAgent.toLowerCase():m,Ya=navigator&&navigator.platform?navigator.platform.toLowerCase():m;z.platform={};
w.T(z,"platform",z.platform);z.platform.lq=Ya?/win/.test(Ya):/win/.test(Xa);w.T(z.platform,"isWin",z.platform.lq);z.platform.WO=!z.platform.lq&&(Ya?/mac/.test(Ya):/mac/.test(Xa));w.T(z.platform,"isMac",z.platform.WO);z.platform.QK="undefined"!=typeof document.getElementById&&"undefined"!=typeof document.getElementsByTagName&&"undefiend"!=typeof document.createElement;w.T(z.platform,"hasDom",z.platform.QK);z.platform.lN=/webkit/.test(Xa)?parseFloat(Xa.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):n;
w.T(z.platform,"webKit",z.platform.lN);z.platform.Ts=/msie/.test(Xa);w.T(z.platform,"isIE",z.platform.Ts);z.platform.hL=/firefox/.test(Xa);w.T(z.platform,"isFirefox",z.platform.hL);z.platform.protocol="https:"==location.protocol?"https:":"http:";w.T(z.platform,"protocol",z.platform.protocol);
z.iL=function(){z.platform.Ki=[0,0,0];var a;if(navigator.plugins&&"object"==typeof navigator.plugins["Shockwave Flash"]){if((a=navigator.plugins["Shockwave Flash"].description)&&(!navigator.mimeTypes||!navigator.mimeTypes[["application/x-shockwave-flash"]]||navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin))a=a.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),z.platform.Ki[0]=parseInt(a.replace(/^(.*)\..*$/,"$1"),10),z.platform.Ki[1]=parseInt(a.replace(/^.*\.(.*)\s.*$/,"$1"),10),z.platform.Ki[2]=
/[a-zA-Z]/.test(a)?parseInt(a.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0}else if("undefined"!=typeof window.ActiveXObject)try{var b=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash");if(b&&(a=b.GetVariable("$version")))a=a.split(" ")[1].split(","),z.platform.Ki=[parseInt(a[0],10),parseInt(a[1],10),parseInt(a[2],10)]}catch(c){}return z.platform.Ki!=m&&9<=Number(z.platform.Ki[0])};w.T(z,"isFlashPlayerValidVersion",z.iL);z.platform.AF=z.iL();w.T(z.platform,"hasRequiredVersion",z.platform.AF);
z.platform.Ki=z.platform.Ki;w.T(z.platform,"flashPlayerVersion",z.platform.Ki);z.platform.rl=z.platform.AF&&z.platform.Ts&&z.platform.lq;w.T(z.platform,"needFormFix",z.platform.rl);z.platform.rl&&(z.platform.rl=9==Number(z.platform.Ki[0]),z.platform.rl=z.platform.rl&&0==Number(z.platform.Ki[1]),z.platform.rl=z.platform.rl&&115>Number(z.platform.Ki[2]));z.yE=[];z.vP=function(a){w.tA(a)&&z.yE.push(a)};w.T(z,"ready",z.vP);
z.cP=function(a){if(a==m||a==h)a=z.sO();var a=a+"AnyChartHTML5.js",b=new Da;b.zI=i;w.C.Za(b,"complete",z.hM,m,z);w.C.Za(b,["error","abort"],z.gM,m,z);b.send(a,"GET",m,"anychart.com")};w.T(z,"loadHTML5Engine",z.cP);z.hM=function(a){var a=a.target,b;try{b=a.Rc?a.Rc.responseText:""}catch(c){b=""}eval(b.toString());b=z.yE.length;for(var e=0;e<b;e++)z.yE[e]();z.YN(a)};z.gM=function(){d(Error("Can not find AnyChart html5 engine in JS folder."))};
z.YN=function(a){w.C.gc(a,"complete",z.hM,m,z);w.C.gc(a,["error","abort"],z.gM,m,z)};z.sO=function(){for(var a=w.global.document.getElementsByTagName("script"),b=a.length-1;b>=0;--b){var c=a[b].src,e=c.lastIndexOf("?"),e=e==-1?c.length:e,c=c.substr(0,e),f=c.split("/"),f=f[f.length-1].toLowerCase(),g=f.length;if(f.indexOf("anychart")!=-1&&f.substr(g-3,3)==".js")return c.substr(0,e-g)}return m};z.P.attachEvent=function(a,b,c){a.attachEvent(b,c);z.P.push(z.P.QS,[a,b,c])};
z.P.AN=function(a,b){if(z.P.zF(window.addEventListener))window.addEventListener(a,b,n);else if(z.P.zF(document.addEventListener))document.addEventListener(a,b,n);else if(z.P.zF(window.attachEvent))z.P.attachEvent(window,"on"+a,b);else if(typeof window["on"+a]=="function"){var c=window["on"+a];window["on"+a]=function(){c();b()}}else window["on"+a]=b};w.gh("AnyChart.utils.addGlobalEventListener",z.P.AN);z.P.Qs=n;z.P.iE=[];z.P.zN=function(a){z.P.Qs?a():z.P.iE.push(a)};
z.P.hs=function(){if(!z.P.Qs){try{var a=document.getElementsByTagName("body")[0].appendChild(document.createElement("span"));a.parentNode.removeChild(a)}catch(b){return}z.P.Qs=i;for(var a=z.P.iE.length,c=0;c<a;c++)z.P.iE[c]()}};
z.P.xP=function(){if(z.platform.QK){typeof document.readyState!="undefined"&&(document.readyState=="complete"||document.getElementsByTagName("body")[0]||document.body)&&z.P.hs();if(!z.P.Qs){document.addEventListener&&document.addEventListener("DOMContentLoaded",z.P.hs,n);if(z.platform.Ts&&z.platform.lq){document.attachEvent("onreadystatechange",function(){if(document.readyState=="complete"){document.detachEvent("onreadystatechange",arguments.callee);z.P.hs()}});window==top&&function(){if(!z.P.Qs){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,
0);return}z.P.hs()}}()}z.platform.lN&&function(){z.P.Qs||(/loaded|complete/.test(document.readyState)?z.P.hs():setTimeout(arguments.callee,0))}();w.C.Za(window,"load",z.P.hs)}}};z.P.xP();z.dispatchEvent=function(a,b){z.nJ(a)&&b!=m&&z.Rr[a].dispatchEvent(b)};w.T(z,"dispatchEvent",z.dispatchEvent);
function Za(a){switch(a.renderingType){case "svg":return new window.anychart.render.svg.SVGRenderer;case "flash":return new Ma;default:case "flashPreferred":return z.platform.hasRequiredVersion?new Ma:new window.anychart.render.svg.SVGRenderer;case "svgPreferred":return window.SVGAngle!=h?new window.anychart.render.svg.SVGRenderer:new Ma}}z.yP=function(a){a.id=a.id==h?"__AnyChart___"+z.Pu.length:a.id;z.Rr[a.id]=a;z.Pu.push(a)};z.nJ=function(a){return a&&z.Rr&&z.Rr[a]};
z.uO=function(a){return z.nJ(a)?z.Rr[a]:m};w.T(z,"getChartById",z.uO);z.fO=function(a,b){z.ds(a,b)};w.T(z,"disposeFlashObject",z.fO);z.ds=function(a,b){a.ds(a,b)};w.T(z,"disposeVisual",z.ds);z.prototype.ds=function(a,b){this.sa.ds(a,b)};z.P.Bf={};w.gh("AnyChart.utils.JSConverter",z.P.Bf);z.P.Bf.WF=function(a){a=typeof a;return a=="string"||a=="number"||a=="boolean"};w.T(z.P.Bf,"isAttribute",z.P.Bf.WF);z.P.Bf.isArray=function(a){return typeof a!="string"&&typeof a.length!="undefined"};
w.T(z.P.Bf,"isArray",z.P.Bf.isArray);z.P.Bf.ON=function(a){return z.P.Bf.PD("anychart",a)};w.T(z.P.Bf,"convert",z.P.Bf.ON);
z.P.Bf.PD=function(a,b){var c,e,f="<"+a;if(typeof b.functionName!="undefined"){b["function"]=b.functionName;delete b.functionName}for(c in b)c!="format"&&c!="text"&&c!="custom_attribute_value"&&c!="attr"&&z.P.Bf.WF(b[c])&&(f=f+(" "+c+'="'+b[c]+'"'));f=f+">";for(c in b)if(c=="arg"&&z.P.Bf.isArray(b[c])){var g=b[c];for(e=0;e<g.length;e++)f=f+("<arg><![CDATA["+g[e]+"]]\></arg>")}else if(c=="custom_attribute_value"||c=="attr")f=f+("<![CDATA["+b[c]+"]]\>");else if(c=="format"||c=="text")f=f+("<"+c+"><![CDATA["+
b[c]+"]]\></"+c+">");else if(z.P.Bf.isArray(b[c])){g=b[c];for(e=0;e<g.length;e++)f=f+z.P.Bf.PD(c,g[e])}else z.P.Bf.WF(b[c])||(f=f+z.P.Bf.PD(c,b[c]));return f+("</"+a+">")};z.messages={};z.messages.preloaderInit=" ";z.messages.preloaderLoading="Loading... ";z.messages.init="Initializing...";z.messages.loadingConfig="Loading config...";z.messages.loadingResources="Loading resources...";z.messages.loadingTemplates="Loading templates...";z.messages.noData="No Data";z.messages.waitingForData="Waiting for data...";
z.watermark=m;z.prototype.hP={};w.T(z.prototype,"messages",z.prototype.hP);z.prototype.messages.preloaderInit=m;z.prototype.messages.preloaderLoading=m;z.prototype.messages.init=m;z.prototype.messages.loadingConfig=m;z.prototype.messages.loadingResources=m;z.prototype.messages.loadingTemplates=m;z.prototype.messages.noData=m;z.prototype.messages.waitingForData=m;z.prototype.addEventListener=function(a,b){this.qe[a]==m&&(this.qe[a]=[]);this.qe[a].push(b)};w.T(z.prototype,"addEventListener",z.prototype.addEventListener);
z.prototype.removeEventListener=function(a,b){if(!(this.qe==m||this.qe[a]==m)){for(var c=-1,e=0;e<this.qe[a].length;e++)if(this.qe[a][e]==b){c=e;break}c!=-1&&this.qe[a].splice(c,1)}};w.T(z.prototype,"removeEventListener",z.prototype.removeEventListener);z.prototype.dispatchEvent=function(a){if(!(a==m||a.type==m)){a.type=="create"?this.sa.dM():a.type=="draw"&&this.sa.eM();a.target=this;if(!(this.qe==m||this.qe[a.type]==m))for(var b=this.qe[a.type].length,c=0;c<b;c++)this.qe[a.type][c](a)}};
w.T(z.prototype,"dispatchEvent",z.prototype.dispatchEvent);z.prototype.mp=function(){return this.sa.mp()};w.T(z.prototype,"canWrite",z.prototype.mp);z.prototype.write=function(a){this.sa=Za(this);this.sa.Pj(this);if(this.mp()){if(a==h){a="__chart_generated_container__"+this.id;document.write('<div id="'+a+'"></div>')}var b=this;z.P.zN(function(){typeof a=="string"?$a(b,document.getElementById(a)):$a(b,a)})}};w.T(z.prototype,"write",z.prototype.write);
function $a(a,b){a.gl=a.sa.write(b);a.gl&&a.Lu()&&(a.xmlFile!=m?a.kj(a.xmlFile):a.jsonFile!=m?a.Oo(a.jsonFile):a.xmlData!=m?a.ox(a.xmlData):a.jsonData!=m&&a.mk(a.jsonData))}z.prototype.Lu=function(){return this.sa.Lu()};w.T(z.prototype,"canSetConfigAfterWrite",z.prototype.Lu);z.prototype.vC=function(){this.sa.vC()};w.T(z.prototype,"updatePrintForFirefox",z.prototype.vC);z.prototype.$q=function(a,b){this.width=a;this.height=b;this.sa.$q(a,b)};w.T(z.prototype,"setSize",z.prototype.$q);
w.gh("AnyChart.prototype.resize",z.prototype.$q);z.prototype.remove=function(){this.sa.remove()};w.T(z.prototype,"remove",z.prototype.remove);z.prototype.clear=function(){this.sa.clear()};w.T(z.prototype,"clear",z.prototype.clear);z.prototype.refresh=function(){this.sa.refresh()};w.T(z.prototype,"refresh",z.prototype.refresh);z.prototype.Yt=function(a,b){this.sa.Yt(a,b)};w.T(z.prototype,"updateData",z.prototype.Yt);z.prototype.LB=function(a){this.sa.LB(a)};w.T(z.prototype,"setLoading",z.prototype.LB);
z.prototype.Fz=function(){return this.sa.Fz()};w.T(z.prototype,"getInformation",z.prototype.Fz);z.prototype.kj=function(a){this.xmlFile=a;this.gl&&this.sa.kj(a)};w.T(z.prototype,"setXMLFile",z.prototype.kj);z.prototype.mi=function(a){this.xmlData=""+a;this.gl&&this.sa.mi(this.xmlData)};w.T(z.prototype,"setXMLData",z.prototype.mi);z.prototype.ox=function(a){this.gl&&this.sa.ox(a)};w.T(z.prototype,"setXMLDataFromString",z.prototype.ox);z.prototype.TB=function(a){this.gl&&this.sa.TB(a)};
w.T(z.prototype,"setXMLDataFromURL",z.prototype.TB);z.prototype.br=function(a,b){this.sa.br(a,b)};w.T(z.prototype,"setViewXMLFile",z.prototype.br);z.prototype.PB=function(a,b){this.sa.PB(a,b)};w.T(z.prototype,"setViewData",z.prototype.PB);z.prototype.Oo=function(a){this.jsonFile=a;this.gl&&this.sa.Oo(a)};w.T(z.prototype,"setJSONFile",z.prototype.Oo);z.prototype.mk=function(a){this.jsonData=a;this.gl&&this.sa.mk(this.jsonData)};w.T(z.prototype,"setJSONData",z.prototype.mk);
w.gh("AnyChart.prototype.setJSData",z.prototype.mk);z.prototype.setData=function(a){if(a!=m){for(var b=""+a;b.charAt(0)==" "&&b.length>0;)b=b.substr(1);if(b.charAt(0)=="<"){this.xmlData=""+a;this.gl&&this.sa.mi(this.xmlData)}else{this.jsonData=a;this.gl&&this.sa.mk(this.jsonData)}}};w.T(z.prototype,"setData",z.prototype.setData);z.prototype.od=function(a,b){this.sa.od(a,b)};w.T(z.prototype,"addPoint",z.prototype.od);z.prototype.Bk=function(a,b,c){this.sa.Bk(a,b,c)};w.T(z.prototype,"addPointAt",z.prototype.Bk);
z.prototype.yl=function(a,b){this.sa.yl(a,b)};w.T(z.prototype,"removePoint",z.prototype.yl);z.prototype.Nl=function(a,b,c){this.sa.Nl(a,b,c)};w.T(z.prototype,"updatePoint",z.prototype.Nl);z.prototype.xk=function(a,b,c){this.sa.xk(a,b,c)};w.T(z.prototype,"updatePointData",z.prototype.xk);z.prototype.bl=function(a,b,c){this.sa.bl(a,b,c)};w.T(z.prototype,"highlightPoint",z.prototype.bl);z.prototype.ik=function(a,b,c){this.sa.ik(a,b,c)};w.T(z.prototype,"selectPoint",z.prototype.ik);
z.prototype.uC=function(a,b,c,e){this.sa.uC(a,b,c,e)};w.T(z.prototype,"updatePointWithAnimation",z.prototype.uC);z.prototype.dC=function(){this.sa.dC()};w.T(z.prototype,"startPointsAnimation",z.prototype.dC);z.prototype.Ck=function(a){this.sa.Ck(a)};w.T(z.prototype,"addSeries",z.prototype.Ck);z.prototype.Dk=function(a,b){this.sa.Dk(a,b)};w.T(z.prototype,"addSeriesAt",z.prototype.Dk);z.prototype.zl=function(a){this.sa.zl(a)};w.T(z.prototype,"removeSeries",z.prototype.zl);
z.prototype.Ol=function(a,b){this.sa.Ol(a,b)};w.T(z.prototype,"updateSeries",z.prototype.Ol);z.prototype.Hl=function(a,b){this.sa.Hl(a,b)};w.T(z.prototype,"showSeries",z.prototype.Hl);z.prototype.cl=function(a,b){this.sa.cl(a,b)};w.T(z.prototype,"highlightSeries",z.prototype.cl);z.prototype.al=function(a,b){this.sa.al(a,b)};w.T(z.prototype,"highlightCategory",z.prototype.al);z.prototype.$B=function(a,b){this.sa.$B(a,b)};w.T(z.prototype,"showAxisMarker",z.prototype.$B);
z.prototype.Dl=function(a,b){this.sa.Dl(a,b)};w.T(z.prototype,"setPlotCustomAttribute",z.prototype.Dl);z.prototype.ou=function(a,b,c){this.sa.ou(a,b,c)};w.T(z.prototype,"view_setPlotCustomAttribute",z.prototype.ou);z.prototype.fu=function(a,b){this.sa.fu(a,b)};w.T(z.prototype,"view_addSeries",z.prototype.fu);z.prototype.mu=function(a,b){this.sa.mu(a,b)};w.T(z.prototype,"view_removeSeries",z.prototype.mu);z.prototype.gu=function(a,b,c){this.sa.gu(a,b,c)};w.T(z.prototype,"view_addSeriesAt",z.prototype.gu);
z.prototype.ru=function(a,b,c){this.sa.ru(a,b,c)};w.T(z.prototype,"view_updateSeries",z.prototype.ru);z.prototype.pu=function(a,b,c){this.sa.pu(a,b,c)};w.T(z.prototype,"view_showSeries",z.prototype.pu);z.prototype.du=function(a,b,c){this.sa.du(a,b,c)};w.T(z.prototype,"view_addPoint",z.prototype.du);z.prototype.eu=function(a,b,c,e){this.sa.eu(a,b,c,e)};w.T(z.prototype,"view_addPointAt",z.prototype.eu);z.prototype.lu=function(a,b,c){this.sa.lu(a,b,c)};w.T(z.prototype,"view_removePoint",z.prototype.lu);
z.prototype.qu=function(a,b,c,e){this.sa.qu(a,b,c,e)};w.T(z.prototype,"view_updatePoint",z.prototype.qu);z.prototype.EC=function(a){this.sa.EC(a)};w.T(z.prototype,"view_clear",z.prototype.EC);z.prototype.ku=function(a){this.sa.ku(a)};w.T(z.prototype,"view_refresh",z.prototype.ku);z.prototype.ju=function(a,b,c){this.sa.ju(a,b,c)};w.T(z.prototype,"view_highlightSeries",z.prototype.ju);z.prototype.iu=function(a,b,c,e){this.sa.iu(a,b,c,e)};w.T(z.prototype,"view_highlightPoint",z.prototype.iu);
z.prototype.hu=function(a,b,c){this.sa.hu(a,b,c)};w.T(z.prototype,"view_highlightCategory",z.prototype.hu);z.prototype.nu=function(a,b,c,e){this.sa.nu(a,b,c,e)};w.T(z.prototype,"view_selectPoint",z.prototype.nu);z.prototype.$t=function(a,b,c,e){this.sa.$t(a,b,c,e)};w.T(z.prototype,"updateViewPointData",z.prototype.$t);z.prototype.zs=function(a,b){if(a==m||a==h)a=NaN;if(b==m||b==h)b=NaN;return this.sa.zs(a,b)};w.T(z.prototype,"getPNG",z.prototype.zs);w.gh("AnyChart.prototype.getPNGImage",z.prototype.zs);
z.prototype.Sz=function(a,b){if(a==m||a==h)a=NaN;if(b==m||b==h)b=NaN;return this.sa.Sz(a,b)};w.T(z.prototype,"getPDF",z.prototype.Sz);z.prototype.pB=function(){this.sa.pB()};w.T(z.prototype,"printChart",z.prototype.pB);z.prototype.CB=function(a,b){if(a==m||a==h)a=NaN;if(b==m||b==h)b=NaN;this.sa.CB(a,b)};w.T(z.prototype,"saveAsImage",z.prototype.CB);z.prototype.DB=function(a,b){if(a==m||a==h)a=NaN;if(b==m||b==h)b=NaN;this.sa.DB(a,b)};w.T(z.prototype,"saveAsPDF",z.prototype.DB);z.prototype.EB=function(a){this.sa.EB(a)};
w.T(z.prototype,"scrollXTo",z.prototype.EB);z.prototype.FB=function(a){this.sa.FB(a)};w.T(z.prototype,"scrollYTo",z.prototype.FB);z.prototype.scrollTo=function(a,b){this.sa.scrollTo(a,b)};w.T(z.prototype,"scrollTo",z.prototype.scrollTo);z.prototype.BC=function(a,b){this.sa.BC(a,b)};w.T(z.prototype,"viewScrollXTo",z.prototype.BC);z.prototype.CC=function(a,b){this.sa.CC(a,b)};w.T(z.prototype,"viewScrollYTo",z.prototype.CC);z.prototype.Yz=function(){return this.sa.Yz()};
w.T(z.prototype,"getXScrollInfo",z.prototype.Yz);z.prototype.Zz=function(){return this.sa.Zz()};w.T(z.prototype,"getYScrollInfo",z.prototype.Zz);z.prototype.Wz=function(a){return this.sa.Wz(a)};w.T(z.prototype,"getViewXScrollInfo",z.prototype.Wz);z.prototype.Xz=function(a){return this.sa.Xz(a)};w.T(z.prototype,"getViewYScrollInfo",z.prototype.Xz);z.prototype.UB=function(a){this.sa.UB(a)};w.T(z.prototype,"setXZoom",z.prototype.UB);z.prototype.VB=function(a){this.sa.VB(a)};
w.T(z.prototype,"setYZoom",z.prototype.VB);z.prototype.WB=function(a,b){this.sa.WB(a,b)};w.T(z.prototype,"setZoom",z.prototype.WB);z.prototype.QB=function(a,b){this.sa.QB(a,b)};w.T(z.prototype,"setViewXZoom",z.prototype.QB);z.prototype.RB=function(a,b){this.sa.RB(a,b)};w.T(z.prototype,"setViewYZoom",z.prototype.RB);z.prototype.SB=function(a,b,c){this.sa.SB(a,b,c)};w.T(z.prototype,"setViewZoom",z.prototype.SB);z.prototype.hy=function(){this.sa.hy()};w.T(z.prototype,"animate",z.prototype.hy);
z.prototype.fd=function(a){return this.sa.fd(a)};w.T(z.prototype,"getSVG",z.prototype.fd);})()
